$axure.loadCurrentPage({
  "url":"操盘申请成功.html",
  "generationDate":new Date(1427013126795.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c35a3869023b4822b0a021df8d71e5a6",
    "type":"Axure:Page",
    "name":"操盘申请成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ff5d716b5bb54d89a1322b915f30a141",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF555555},
            "size":{
              "width":1235,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d7ec7d19f854190b39df1b4b8985541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF555555},
                "size":{
                  "width":1235,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（登陆后）/u10.png"}},
{
          "id":"fa7e376829c24d32a2be4dbb623455ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF0F4F7},
            "location":{
              "x":0,
              "y":50},
            "size":{
              "width":1235,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a90a8f18b0b445eadc0e68752572555",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF0F4F7},
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":1235,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按天配资/u4.png"}},
{
          "id":"8795e0f8f2ba49fe935830232a1f6eaa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":118,
              "y":63},
            "size":{
              "width":143,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4082e5f54814e23958bc5b8b3e87944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":118,
                  "y":63},
                "size":{
                  "width":143,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（登陆后）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（登陆后）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页（登陆后）/u18.png"}},
{
          "id":"271fcc84ea184d22828b7092e1fbbe2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":278,
              "y":80},
            "size":{
              "width":241,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec012b5acd94eb488bb4eec6d3c0aca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":278,
                  "y":80},
                "size":{
                  "width":241,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9464e45c9f334f97b04dd59482f3d0c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":742,
              "y":81},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda9b5a9610044f98b8b3dc4409d61b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":742,
                  "y":81},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（登陆后）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（登陆后）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"760ac6a8e9a74c668dd2e20fbb2bdf6f",
          "label":"我的账号",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":15},
            "size":{
              "width":78,
              "height":22}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9a8f8209f0d74632b022f6156f997abc",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f032d2a0893a4f2f89f07052d69a2ecc",
                  "label":"",
                  "parentDynamicPanel":"760ac6a8e9a74c668dd2e20fbb2bdf6f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF555555},
                    "size":{
                      "width":80,
                      "height":22},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d23f1da5538248e0a1c05c1f90c1b7a8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"760ac6a8e9a74c668dd2e20fbb2bdf6f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF555555},
                        "size":{
                          "width":80,
                          "height":22},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示/隐藏部件",
                              "objectsToFades":[]}]}]}},
                  "images":{
                    "normal~":"images/首页（登陆后）/u227.png"}},
{
                  "id":"9fc56c3c52ff4891b31d104a9004c3e4",
                  "label":"",
                  "parentDynamicPanel":"760ac6a8e9a74c668dd2e20fbb2bdf6f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":68,
                      "y":7},
                    "size":{
                      "width":8,
                      "height":8},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dcce44549b6c4e5e882189ac9206b436",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"760ac6a8e9a74c668dd2e20fbb2bdf6f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":68,
                          "y":7},
                        "size":{
                          "width":8,
                          "height":8},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页（登陆后）/u229.png"}}]},
{
              "id":"4caf4ba357c94f00b285423625108183",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[]}]},
{
          "id":"2bbf08b6ff1a4cbf8463723eb217b054",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":900,
              "y":14},
            "size":{
              "width":85,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf67be0021c840c8989c49d373986852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":900,
                  "y":14},
                "size":{
                  "width":85,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（登陆后）/u255.png"}},
{
          "id":"f268ce38beec44b5aaf8111108efb8f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF555555},
            "location":{
              "x":987,
              "y":15},
            "size":{
              "width":96,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad4da8c391a4f9d898eaec6b01db79d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF555555},
                "location":{
                  "x":987,
                  "y":15},
                "size":{
                  "width":96,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页（登陆后）/u257.png"}},
{
          "id":"04c2d3b4bb8944a9a4364aef4a9821c6",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":18},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/按天配资/u25_line.png"}},
{
          "id":"c217798e23c44440982e7364ccf81072",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":144,
              "y":242},
            "size":{
              "width":170,
              "height":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a4b8eab46e542738dcbc3e7c4446284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":144,
                  "y":242},
                "size":{
                  "width":170,
                  "height":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付保证金和管理费（余额不足时）/u21.png"}},
{
          "id":"5ad1fc9a7f594c6b9426330a119c8c8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":179,
              "y":388},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c167ed8e3454d8f964a63c21b7f3c8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":179,
                  "y":388},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"392244799a914da091a7530639bfbb9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":314,
              "y":242},
            "size":{
              "width":783,
              "height":310},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"259ed660bc694e0096703d3c9785afb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":314,
                  "y":242},
                "size":{
                  "width":783,
                  "height":310},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付保证金和管理费（余额不足时）/u25.png"}},
{
          "id":"61d06ff455674a2abcc9b7aec866247c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":506,
              "y":355},
            "size":{
              "width":469,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3373d0e8d9fc439ba88db7a30397d744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":506,
                  "y":355},
                "size":{
                  "width":469,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6a4be7523fe46deafdf96eac4fd8fdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":506,
              "y":314},
            "size":{
              "width":343,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bf8e53589c14e6e88ee646ad8cbe06f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":506,
                  "y":314},
                "size":{
                  "width":343,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e687472d0ee1448aae4a25dbefcba037",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":506,
              "y":407},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a27a589da0be4af7bec1a810b829fd30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":506,
                  "y":407},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f57a371192cd40ccb8c12cad856ae7af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "location":{
              "x":638,
              "y":407},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a7b26b6d3f042a39c218f8149972e16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "location":{
                  "x":638,
                  "y":407},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页（登陆后）",
                      "target":{
                        "targetType":"page",
                        "url":"首页（登陆后）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a39549c169b447c987bb91872fb4ee54",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":613,
              "y":407},
            "size":{
              "width":10,
              "height":19},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/操盘申请成功/u34_line.png"}},
{
          "id":"711c6d8140a54dbab6c45e717a393f93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":155,
              "y":193},
            "size":{
              "width":193,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04e75465e36448edabe418f572450722",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":155,
                  "y":193},
                "size":{
                  "width":193,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccd4143474834a0b891df0675e1aec06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":363,
              "y":193},
            "size":{
              "width":85,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba9e2d5bfac4400ca61586641bbe2abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":363,
                  "y":193},
                "size":{
                  "width":85,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aec2b2ad9824ebdbedbe562b36d8334",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":562,
              "y":194},
            "size":{
              "width":189,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2081666809346d4986d9c442f77fdb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":562,
                  "y":194},
                "size":{
                  "width":189,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7778aa8b3ca64c84b908be991d1ab8c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":782,
              "y":194},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8083c8da9a146c0b148bc15c5dd1600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":782,
                  "y":194},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31a88768816e4cbf832272bb44ab0200",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":973,
              "y":194},
            "size":{
              "width":71,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4819a9f01c94d4b9384e4d1d88da3b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":973,
                  "y":194},
                "size":{
                  "width":71,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"918431522d8c4b478a9db367041fc299",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":160},
            "size":{
              "width":645,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acdc87e34e0745229c9e228d1e65acb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":160},
                "size":{
                  "width":645,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按天配资/u100.png"}},
{
          "id":"dc39ed9bc0354ec59302d8cba529220f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":828,
              "y":156},
            "size":{
              "width":200,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2aa78fdf4c3a496ab28f95fcd8415a8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":828,
                  "y":156},
                "size":{
                  "width":200,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/按天配资/u102.png"}},
{
          "id":"e9efc3d587a84c8e842e331329d73640",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":448,
              "y":194},
            "size":{
              "width":91,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c72e006bfc1c4695b17a0a45c787e7b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "location":{
                  "x":448,
                  "y":194},
                "size":{
                  "width":91,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38dbc8762365438e8a3f09b54b38cdc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":592,
              "y":159},
            "size":{
              "width":38,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4977ddf13aed438a80f34734dc5333d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":592,
                  "y":159},
                "size":{
                  "width":38,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操盘申请成功/u51.png"}},
{
          "id":"72d99037fc434b40869e458116df1ceb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":160},
            "size":{
              "width":75,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ab23d76965f41c2ab9d99d198ffda78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":160},
                "size":{
                  "width":75,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操盘申请成功/u53.png"}},
{
          "id":"93b31767f4e74da6b96aac2a2f96ff2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":159},
            "size":{
              "width":38,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a794cd16ed634d7bafef9f8495be5dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":159},
                "size":{
                  "width":38,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操盘申请成功/u51.png"}},
{
          "id":"1cf151519d5145b8a50a81271fa40312",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":424,
              "y":160},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2a836ca8789406bb1802f380e2488f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":424,
                  "y":160},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操盘申请成功/u57.png"}},
{
          "id":"c11c85a706f840b0bbae18760ffcaeff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":630,
              "y":154},
            "size":{
              "width":90,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e184e8b2b3c4b488a19905e9c0b8e38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":630,
                  "y":154},
                "size":{
                  "width":90,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/操盘申请成功/u59.png"}},
{
          "id":"c2490168585648ab8eea19b6c8869bbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":800,
              "y":83},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6df9cacba12349b6b9947f189211a2ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":800,
                  "y":83},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 按天配资",
                      "target":{
                        "targetType":"page",
                        "url":"按天配资.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc91c7ac6c6d4b81b574411dbcdb7286",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":883,
              "y":83},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b3573c5895c40279b3ea21e1e440668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":883,
                  "y":83},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 按月配资",
                      "target":{
                        "targetType":"page",
                        "url":"按月配资.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"313675b16fa44871bb256e98a62b1915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1042,
              "y":81},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca158835c66c4e94aa430e8f902a9a05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1042,
                  "y":81},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 配置介绍",
                      "target":{
                        "targetType":"page",
                        "url":"配置介绍.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"187e329544fa4758b82c325db6fb3795",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":961,
              "y":81},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"973efbd8f374454cb1a4428d4729530c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":961,
                  "y":81},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 安全保障",
                      "target":{
                        "targetType":"page",
                        "url":"安全保障.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94d92b4d94d34763971e88d46f632de0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":18},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/按天配资/u25_line.png"}},
{
          "id":"47478541cf0944129866a3b70a8f6de9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":18},
            "size":{
              "width":10,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/按天配资/u25_line.png"}},
{
          "id":"b9de2a44d6bb4919888846f64b8a4420",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":211,
              "y":18},
            "size":{
              "width":57,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"152bf01d83f6426bae14a4914c5f27ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":211,
                  "y":18},
                "size":{
                  "width":57,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1dda82130447d2ad9ad1b668828073",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":154,
              "y":18},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a995dc3adbf43f89603857e4ecedf41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":154,
                  "y":18},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ff5d716b5bb54d89a1322b915f30a141":{
      "scriptId":"u0"},
    "8d7ec7d19f854190b39df1b4b8985541":{
      "scriptId":"u1"},
    "fa7e376829c24d32a2be4dbb623455ba":{
      "scriptId":"u2"},
    "4a90a8f18b0b445eadc0e68752572555":{
      "scriptId":"u3"},
    "8795e0f8f2ba49fe935830232a1f6eaa":{
      "scriptId":"u4"},
    "c4082e5f54814e23958bc5b8b3e87944":{
      "scriptId":"u5"},
    "271fcc84ea184d22828b7092e1fbbe2f":{
      "scriptId":"u6"},
    "0ec012b5acd94eb488bb4eec6d3c0aca":{
      "scriptId":"u7"},
    "9464e45c9f334f97b04dd59482f3d0c8":{
      "scriptId":"u8"},
    "fda9b5a9610044f98b8b3dc4409d61b6":{
      "scriptId":"u9"},
    "760ac6a8e9a74c668dd2e20fbb2bdf6f":{
      "scriptId":"u10"},
    "f032d2a0893a4f2f89f07052d69a2ecc":{
      "scriptId":"u11"},
    "d23f1da5538248e0a1c05c1f90c1b7a8":{
      "scriptId":"u12"},
    "9fc56c3c52ff4891b31d104a9004c3e4":{
      "scriptId":"u13"},
    "dcce44549b6c4e5e882189ac9206b436":{
      "scriptId":"u14"},
    "2bbf08b6ff1a4cbf8463723eb217b054":{
      "scriptId":"u15"},
    "cf67be0021c840c8989c49d373986852":{
      "scriptId":"u16"},
    "f268ce38beec44b5aaf8111108efb8f1":{
      "scriptId":"u17"},
    "8ad4da8c391a4f9d898eaec6b01db79d":{
      "scriptId":"u18"},
    "04c2d3b4bb8944a9a4364aef4a9821c6":{
      "scriptId":"u19"},
    "c217798e23c44440982e7364ccf81072":{
      "scriptId":"u20"},
    "7a4b8eab46e542738dcbc3e7c4446284":{
      "scriptId":"u21"},
    "5ad1fc9a7f594c6b9426330a119c8c8a":{
      "scriptId":"u22"},
    "9c167ed8e3454d8f964a63c21b7f3c8a":{
      "scriptId":"u23"},
    "392244799a914da091a7530639bfbb9b":{
      "scriptId":"u24"},
    "259ed660bc694e0096703d3c9785afb3":{
      "scriptId":"u25"},
    "61d06ff455674a2abcc9b7aec866247c":{
      "scriptId":"u26"},
    "3373d0e8d9fc439ba88db7a30397d744":{
      "scriptId":"u27"},
    "e6a4be7523fe46deafdf96eac4fd8fdd":{
      "scriptId":"u28"},
    "7bf8e53589c14e6e88ee646ad8cbe06f":{
      "scriptId":"u29"},
    "e687472d0ee1448aae4a25dbefcba037":{
      "scriptId":"u30"},
    "a27a589da0be4af7bec1a810b829fd30":{
      "scriptId":"u31"},
    "f57a371192cd40ccb8c12cad856ae7af":{
      "scriptId":"u32"},
    "7a7b26b6d3f042a39c218f8149972e16":{
      "scriptId":"u33"},
    "a39549c169b447c987bb91872fb4ee54":{
      "scriptId":"u34"},
    "711c6d8140a54dbab6c45e717a393f93":{
      "scriptId":"u35"},
    "04e75465e36448edabe418f572450722":{
      "scriptId":"u36"},
    "ccd4143474834a0b891df0675e1aec06":{
      "scriptId":"u37"},
    "ba9e2d5bfac4400ca61586641bbe2abf":{
      "scriptId":"u38"},
    "6aec2b2ad9824ebdbedbe562b36d8334":{
      "scriptId":"u39"},
    "f2081666809346d4986d9c442f77fdb0":{
      "scriptId":"u40"},
    "7778aa8b3ca64c84b908be991d1ab8c1":{
      "scriptId":"u41"},
    "a8083c8da9a146c0b148bc15c5dd1600":{
      "scriptId":"u42"},
    "31a88768816e4cbf832272bb44ab0200":{
      "scriptId":"u43"},
    "b4819a9f01c94d4b9384e4d1d88da3b4":{
      "scriptId":"u44"},
    "918431522d8c4b478a9db367041fc299":{
      "scriptId":"u45"},
    "acdc87e34e0745229c9e228d1e65acb6":{
      "scriptId":"u46"},
    "dc39ed9bc0354ec59302d8cba529220f":{
      "scriptId":"u47"},
    "2aa78fdf4c3a496ab28f95fcd8415a8a":{
      "scriptId":"u48"},
    "e9efc3d587a84c8e842e331329d73640":{
      "scriptId":"u49"},
    "c72e006bfc1c4695b17a0a45c787e7b9":{
      "scriptId":"u50"},
    "38dbc8762365438e8a3f09b54b38cdc9":{
      "scriptId":"u51"},
    "4977ddf13aed438a80f34734dc5333d8":{
      "scriptId":"u52"},
    "72d99037fc434b40869e458116df1ceb":{
      "scriptId":"u53"},
    "5ab23d76965f41c2ab9d99d198ffda78":{
      "scriptId":"u54"},
    "93b31767f4e74da6b96aac2a2f96ff2b":{
      "scriptId":"u55"},
    "a794cd16ed634d7bafef9f8495be5dae":{
      "scriptId":"u56"},
    "1cf151519d5145b8a50a81271fa40312":{
      "scriptId":"u57"},
    "e2a836ca8789406bb1802f380e2488f3":{
      "scriptId":"u58"},
    "c11c85a706f840b0bbae18760ffcaeff":{
      "scriptId":"u59"},
    "9e184e8b2b3c4b488a19905e9c0b8e38":{
      "scriptId":"u60"},
    "c2490168585648ab8eea19b6c8869bbe":{
      "scriptId":"u61"},
    "6df9cacba12349b6b9947f189211a2ed":{
      "scriptId":"u62"},
    "dc91c7ac6c6d4b81b574411dbcdb7286":{
      "scriptId":"u63"},
    "1b3573c5895c40279b3ea21e1e440668":{
      "scriptId":"u64"},
    "313675b16fa44871bb256e98a62b1915":{
      "scriptId":"u65"},
    "ca158835c66c4e94aa430e8f902a9a05":{
      "scriptId":"u66"},
    "187e329544fa4758b82c325db6fb3795":{
      "scriptId":"u67"},
    "973efbd8f374454cb1a4428d4729530c":{
      "scriptId":"u68"},
    "94d92b4d94d34763971e88d46f632de0":{
      "scriptId":"u69"},
    "47478541cf0944129866a3b70a8f6de9":{
      "scriptId":"u70"},
    "b9de2a44d6bb4919888846f64b8a4420":{
      "scriptId":"u71"},
    "152bf01d83f6426bae14a4914c5f27ce":{
      "scriptId":"u72"},
    "3e1dda82130447d2ad9ad1b668828073":{
      "scriptId":"u73"},
    "0a995dc3adbf43f89603857e4ecedf41":{
      "scriptId":"u74"}}});