$axure.loadCurrentPage({
  "url":"修改竞彩篮球赛程.html",
  "generationDate":new Date(1420340062898.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"87b1d2b3de4a4abab710650e3e2674fe",
    "type":"Axure:Page",
    "name":"修改竞彩篮球赛程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c25d00e6cb1f488a8e6dd87a52ecb111",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":412},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef999a386c304f6b9336a3590a40dfc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":412},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"95dadcc1564745f7a8aaa8d4ea232376",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":417},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"211"},
{
          "id":"962830abdf73497caf6460b0199b07ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":412},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5191fdbc5d184950b5178ecf51dd0649",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":412},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"d366681800824ebc9ad8bd3f05cfe30e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":140},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07fdf01699d243498c230427c0e1af70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":140},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"58b9b875b9074d17af6967a05ca098d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":729,
              "y":140},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae290b17866842ed93fb2d1700612909",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":729,
                  "y":140},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"63910690706d4f4c9613fc6bf94cb290",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":174},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172808202bc94d65a875e15324a62578",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":174},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"cc0ab335d0f442398100fc5bb9600d5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":174},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db73abc9b13498f8b2e1a3e9d5fc652",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":174},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"06aa7dd6a516459caf96847af2e4e60d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":179},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"NBA"},
{
          "id":"5c17a362d8114a35b920fc159afacbc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":208},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddd3dc5cee92472fa9183d91fff8eb3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":208},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"52ba93a78df54a3ea09cb08b32dee86b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":208},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab32d809b45148909910f51b040fe6cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":208},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"da23cdbf9ebc4945b7ff8af25031c826",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":212},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 1",
                      "objectsToFades":[{
                          "objectPath":["edb6b12d6a954074b9a581d08b383578"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 2",
                      "objectsToFades":[{
                          "objectPath":["429a89257e7748aa9aadaa4cdd8dafdc"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "placeholderText":"2014-12-24 07:58:00"},
{
          "id":"10960cc6174a4ce28d8eb44cd7be4d6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":310},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"941a206958d045ff8eee2be037421760",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":310},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"f45d80f751004936a9e24dd4810a7faa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":310},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04d45d7389e64ce3a9a253a28e7c62f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":310},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"9b2bc3a31d204f4cb4ff6f70ca80c4b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":344},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea554deeb076432c89efe6eac5006de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":344},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"2b16d1c48b99428ab0aa3a3cc51901ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":344},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca0323b3fb6d4d66807abe3aaf3538ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":344},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"8cdfc699a29240e8ae48c6ca0a1c6780",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":315},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"骑士"},
{
          "id":"1123f2c902f24251b34b99ab63112064",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":349},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"-6.5"},
{
          "id":"1e4f18de27ee41f8a4cc931e82681d8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":378},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3da2a20834094c9cbb420ecc09273632",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":378},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"1a9d9937ffa54014b6a08231ec68aa49",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":378},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d4716fcefa143f78c115ba4efb77ddc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":378},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"fd0fdcd4476b419b9bc2ceefc105ac43",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":383},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"热火"},
{
          "id":"df1ac1e9905647e78f841700cd24591c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFAFDFE},
{
                  "color":0xFFFAFDFE},
{
                  "color":0xFFBEDCEF},
{
                  "color":0xFFBEDCEF}]},
            "location":{
              "x":700,
              "y":494},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF66FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a73c0651f84d61abe43062efac7f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFAFDFE},
{
                      "color":0xFFFAFDFE},
{
                      "color":0xFFBEDCEF},
{
                      "color":0xFFBEDCEF}]},
                "location":{
                  "x":700,
                  "y":494},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF66FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 竞彩足球",
                      "target":{
                        "targetType":"page",
                        "url":"竞彩足球.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改竞彩足球赛程/u29.png"}},
{
          "id":"6bfec8fcbd72470dbe27fc981ce85c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFFFAFDFE},
{
                  "color":0xFFFAFDFE},
{
                  "color":0xFFBEDCEF},
{
                  "color":0xFFBEDCEF}]},
            "location":{
              "x":830,
              "y":494},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF66FF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164a38c352d640149021f2efb9b4e283",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFFFAFDFE},
{
                      "color":0xFFFAFDFE},
{
                      "color":0xFFBEDCEF},
{
                      "color":0xFFBEDCEF}]},
                "location":{
                  "x":830,
                  "y":494},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF66FF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 竞彩足球",
                      "target":{
                        "targetType":"page",
                        "url":"竞彩足球.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/修改竞彩足球赛程/u29.png"}},
{
          "id":"2be1859f5b4d4b4e9bda4cea59a03539",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":242},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c087d41a8414a778ff7aab72becea9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":242},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"3b8f4657687d457b82af211f7644f9e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":242},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeec35c2721149f6ac474983baccd01e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":242},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"4b1ef23f9bb64915a9eb77b6b4b4d110",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":246},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 2",
                      "objectsToFades":[{
                          "objectPath":["429a89257e7748aa9aadaa4cdd8dafdc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 1",
                      "objectsToFades":[{
                          "objectPath":["edb6b12d6a954074b9a581d08b383578"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "placeholderText":"2014-12-25 09:58:00"},
{
          "id":"cc2d426f60b34d6080cdbb7ce17cb90b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":530,
              "y":276},
            "size":{
              "width":200,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e36334af01814479af8c4ac62ab399ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":530,
                  "y":276},
                "size":{
                  "width":200,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u0.png"}},
{
          "id":"494552dfeda94fab9f306104de2297a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":729,
              "y":276},
            "size":{
              "width":471,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5ca31cfc7004317872ad603962f079d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":729,
                  "y":276},
                "size":{
                  "width":471,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/修改竞彩足球赛程/u2.png"}},
{
          "id":"0ecb9a29f6a84e9397a01b4752753d11",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":742,
              "y":281},
            "size":{
              "width":200,
              "height":24}},
          "adaptiveStyles":{
}},
{
          "id":"edb6b12d6a954074b9a581d08b383578",
          "label":"1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":742,
              "y":237},
            "size":{
              "width":200,
              "height":200},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3ffd926f31094387b96d28a7a815e4ec",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"da68516a88d94ee3a52e3a49f466651b",
                  "label":"",
                  "parentDynamicPanel":"edb6b12d6a954074b9a581d08b383578",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":190,
                      "height":202}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"757916b5bd514f5792328ef296161c8b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edb6b12d6a954074b9a581d08b383578",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":190,
                          "height":202}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 1",
                              "objectsToFades":[{
                                  "objectPath":["edb6b12d6a954074b9a581d08b383578"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改竞彩足球赛程/u44.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"429a89257e7748aa9aadaa4cdd8dafdc",
          "label":"2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":742,
              "y":271},
            "size":{
              "width":200,
              "height":200},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"a193f85aa2394b20883e6026a612dfab",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f6f9bca8dfb342d585bef6ea9931523c",
                  "label":"",
                  "parentDynamicPanel":"429a89257e7748aa9aadaa4cdd8dafdc",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":190,
                      "height":202}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"22107d6112e14bec9ab9988659182404",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"429a89257e7748aa9aadaa4cdd8dafdc",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":190,
                          "height":202}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 2",
                              "objectsToFades":[{
                                  "objectPath":["429a89257e7748aa9aadaa4cdd8dafdc"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/修改竞彩足球赛程/u44.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"ddf8f646f0ed46728c6fc54d8810d19e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":248},
            "size":{
              "width":39,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9b2fff40d87a465a95f39a94b2218648",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":996,
              "y":251},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5a900b276a647928da4a4027381c46c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":996,
                  "y":251},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a6d562c040241d2a320d190dccad517",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":248},
            "size":{
              "width":39,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"ee1144571bb34b44b5a8ad53d4102d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1063,
              "y":251},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efc4ce92701c43b2b011ce625a63d31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1063,
                  "y":251},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51443d6293d74b3baa3ecd063f2064d9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1095,
              "y":248},
            "size":{
              "width":39,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"557c2d6897654c8b80a70b78148035f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1138,
              "y":251},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"005cc004f28e425a98b9c364e07311f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1138,
                  "y":251},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"567f5fa52a32472995e3a9427b62bc94",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":952,
              "y":215},
            "size":{
              "width":39,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"dd052d42da5d44dd94b2b37f0a5c6542",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":996,
              "y":218},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd05dd5d62aa455aadfc42b4db7cd4b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":996,
                  "y":218},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7bb096e9abd403e8a5781a6c35bd43d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1020,
              "y":215},
            "size":{
              "width":39,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"991d679cb66943879ff86887c5009975",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1063,
              "y":218},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cc54ca3579045469b5ac1975e7d38f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1063,
                  "y":218},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bb5575834c24fcb98def4e9b9db19e9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1095,
              "y":215},
            "size":{
              "width":39,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"bbe5607df583420180263bcee8cd5ce2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1138,
              "y":218},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1478f3b5b8af49aa9d0c7008228ba3c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1138,
                  "y":218},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"33a5b924ca4644f4ac31f4c3a36b121d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":743,
              "y":147},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"696a4f3fad1d40518cc80d238295f2df",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":951,
              "y":145},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"001"},
{
          "id":"3afc86b351454e79a92cadaa6faaa7ed",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"ed4f333536ea40f59c9c38d97579f5fc"}]}},
  "masters":{
    "ed4f333536ea40f59c9c38d97579f5fc":{
      "packageId":"ed4f333536ea40f59c9c38d97579f5fc",
      "type":"Axure:Master",
      "name":"竞彩篮球",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a21f855c285546afbe17b18ce85b3115",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":255,
                "height":130},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"949de136652e4587aaa28f6f15834e0c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":255,
                    "height":130},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/竞彩足球/u520.png"}},
{
            "id":"531b5bd5969249cabd327dee67defa54",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":280,
                "y":36},
              "size":{
                "width":1340,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/竞彩篮球/u888_line.png"}},
{
            "id":"65888fe13bce4478a562495d426b9bc3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF66CCFF},
              "location":{
                "x":280,
                "y":2},
              "size":{
                "width":180,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e76207fdbfe4764916e241645779d7a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF66CCFF},
                  "location":{
                    "x":280,
                    "y":2},
                  "size":{
                    "width":180,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/竞彩足球/u523.png"}},
{
            "id":"43b3baab91a245fa8c997f6b3b351b5e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF428BCA},
              "location":{
                "x":10,
                "y":71},
              "size":{
                "width":220,
                "height":40},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c44cddef4fba4676831e174309a3584a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF428BCA},
                  "location":{
                    "x":10,
                    "y":71},
                  "size":{
                    "width":220,
                    "height":40},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 竞彩篮球",
                        "target":{
                          "targetType":"page",
                          "url":"竞彩篮球.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/竞彩足球/u525.png"}},
{
            "id":"69cab1e7e91d4a2fa544dee179da730e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF428BCA},
              "location":{
                "x":10,
                "y":19},
              "size":{
                "width":220,
                "height":40},
              "cornerRadiusTopLeft":"4"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"20f4668cdfbf4c429ea0623b4820e6c8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF428BCA},
                  "location":{
                    "x":10,
                    "y":19},
                  "size":{
                    "width":220,
                    "height":40},
                  "cornerRadiusTopLeft":"4"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 竞彩足球",
                        "target":{
                          "targetType":"page",
                          "url":"竞彩足球.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/竞彩足球/u525.png"}},
{
            "id":"fbbf3217aa1d44e8a76d1f8af2b3978d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF66CCFF},
              "location":{
                "x":1467,
                "y":2},
              "size":{
                "width":130,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "cornerRadiusTopLeft":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"21d3654616324d5d81e4d55d0ca8423b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF66CCFF},
                  "location":{
                    "x":1467,
                    "y":2},
                  "size":{
                    "width":130,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "cornerRadiusTopLeft":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 本站截止时间设置",
                        "target":{
                          "targetType":"page",
                          "url":"本站截止时间设置.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/竞彩足球/u529.png"}},
{
            "id":"5f38062c4ab846cba118e63217fbb521",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF66CCFF},
              "location":{
                "x":1335,
                "y":2},
              "size":{
                "width":130,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "cornerRadiusTopLeft":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b171cf7f062487e9fda983e4ba64ca2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF66CCFF},
                  "location":{
                    "x":1335,
                    "y":2},
                  "size":{
                    "width":130,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "cornerRadiusTopLeft":"2"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 官方开售时间设置",
                        "target":{
                          "targetType":"page",
                          "url":"官方开售时间设置.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/竞彩足球/u529.png"}}]}}},
  "objectPaths":{
    "c25d00e6cb1f488a8e6dd87a52ecb111":{
      "scriptId":"u0"},
    "ef999a386c304f6b9336a3590a40dfc5":{
      "scriptId":"u1"},
    "95dadcc1564745f7a8aaa8d4ea232376":{
      "scriptId":"u2"},
    "962830abdf73497caf6460b0199b07ac":{
      "scriptId":"u3"},
    "5191fdbc5d184950b5178ecf51dd0649":{
      "scriptId":"u4"},
    "d366681800824ebc9ad8bd3f05cfe30e":{
      "scriptId":"u5"},
    "07fdf01699d243498c230427c0e1af70":{
      "scriptId":"u6"},
    "58b9b875b9074d17af6967a05ca098d3":{
      "scriptId":"u7"},
    "ae290b17866842ed93fb2d1700612909":{
      "scriptId":"u8"},
    "63910690706d4f4c9613fc6bf94cb290":{
      "scriptId":"u9"},
    "172808202bc94d65a875e15324a62578":{
      "scriptId":"u10"},
    "cc0ab335d0f442398100fc5bb9600d5f":{
      "scriptId":"u11"},
    "1db73abc9b13498f8b2e1a3e9d5fc652":{
      "scriptId":"u12"},
    "06aa7dd6a516459caf96847af2e4e60d":{
      "scriptId":"u13"},
    "5c17a362d8114a35b920fc159afacbc5":{
      "scriptId":"u14"},
    "ddd3dc5cee92472fa9183d91fff8eb3c":{
      "scriptId":"u15"},
    "52ba93a78df54a3ea09cb08b32dee86b":{
      "scriptId":"u16"},
    "ab32d809b45148909910f51b040fe6cd":{
      "scriptId":"u17"},
    "da23cdbf9ebc4945b7ff8af25031c826":{
      "scriptId":"u18"},
    "10960cc6174a4ce28d8eb44cd7be4d6a":{
      "scriptId":"u19"},
    "941a206958d045ff8eee2be037421760":{
      "scriptId":"u20"},
    "f45d80f751004936a9e24dd4810a7faa":{
      "scriptId":"u21"},
    "04d45d7389e64ce3a9a253a28e7c62f8":{
      "scriptId":"u22"},
    "9b2bc3a31d204f4cb4ff6f70ca80c4b7":{
      "scriptId":"u23"},
    "ea554deeb076432c89efe6eac5006de6":{
      "scriptId":"u24"},
    "2b16d1c48b99428ab0aa3a3cc51901ab":{
      "scriptId":"u25"},
    "ca0323b3fb6d4d66807abe3aaf3538ff":{
      "scriptId":"u26"},
    "8cdfc699a29240e8ae48c6ca0a1c6780":{
      "scriptId":"u27"},
    "1123f2c902f24251b34b99ab63112064":{
      "scriptId":"u28"},
    "1e4f18de27ee41f8a4cc931e82681d8c":{
      "scriptId":"u29"},
    "3da2a20834094c9cbb420ecc09273632":{
      "scriptId":"u30"},
    "1a9d9937ffa54014b6a08231ec68aa49":{
      "scriptId":"u31"},
    "0d4716fcefa143f78c115ba4efb77ddc":{
      "scriptId":"u32"},
    "fd0fdcd4476b419b9bc2ceefc105ac43":{
      "scriptId":"u33"},
    "df1ac1e9905647e78f841700cd24591c":{
      "scriptId":"u34"},
    "01a73c0651f84d61abe43062efac7f00":{
      "scriptId":"u35"},
    "6bfec8fcbd72470dbe27fc981ce85c44":{
      "scriptId":"u36"},
    "164a38c352d640149021f2efb9b4e283":{
      "scriptId":"u37"},
    "2be1859f5b4d4b4e9bda4cea59a03539":{
      "scriptId":"u38"},
    "3c087d41a8414a778ff7aab72becea9a":{
      "scriptId":"u39"},
    "3b8f4657687d457b82af211f7644f9e2":{
      "scriptId":"u40"},
    "aeec35c2721149f6ac474983baccd01e":{
      "scriptId":"u41"},
    "4b1ef23f9bb64915a9eb77b6b4b4d110":{
      "scriptId":"u42"},
    "cc2d426f60b34d6080cdbb7ce17cb90b":{
      "scriptId":"u43"},
    "e36334af01814479af8c4ac62ab399ed":{
      "scriptId":"u44"},
    "494552dfeda94fab9f306104de2297a9":{
      "scriptId":"u45"},
    "b5ca31cfc7004317872ad603962f079d":{
      "scriptId":"u46"},
    "0ecb9a29f6a84e9397a01b4752753d11":{
      "scriptId":"u47"},
    "edb6b12d6a954074b9a581d08b383578":{
      "scriptId":"u48"},
    "da68516a88d94ee3a52e3a49f466651b":{
      "scriptId":"u49"},
    "757916b5bd514f5792328ef296161c8b":{
      "scriptId":"u50"},
    "429a89257e7748aa9aadaa4cdd8dafdc":{
      "scriptId":"u51"},
    "f6f9bca8dfb342d585bef6ea9931523c":{
      "scriptId":"u52"},
    "22107d6112e14bec9ab9988659182404":{
      "scriptId":"u53"},
    "ddf8f646f0ed46728c6fc54d8810d19e":{
      "scriptId":"u54"},
    "9b2fff40d87a465a95f39a94b2218648":{
      "scriptId":"u55"},
    "b5a900b276a647928da4a4027381c46c":{
      "scriptId":"u56"},
    "0a6d562c040241d2a320d190dccad517":{
      "scriptId":"u57"},
    "ee1144571bb34b44b5a8ad53d4102d26":{
      "scriptId":"u58"},
    "efc4ce92701c43b2b011ce625a63d31a":{
      "scriptId":"u59"},
    "51443d6293d74b3baa3ecd063f2064d9":{
      "scriptId":"u60"},
    "557c2d6897654c8b80a70b78148035f7":{
      "scriptId":"u61"},
    "005cc004f28e425a98b9c364e07311f1":{
      "scriptId":"u62"},
    "567f5fa52a32472995e3a9427b62bc94":{
      "scriptId":"u63"},
    "dd052d42da5d44dd94b2b37f0a5c6542":{
      "scriptId":"u64"},
    "dd05dd5d62aa455aadfc42b4db7cd4b3":{
      "scriptId":"u65"},
    "e7bb096e9abd403e8a5781a6c35bd43d":{
      "scriptId":"u66"},
    "991d679cb66943879ff86887c5009975":{
      "scriptId":"u67"},
    "0cc54ca3579045469b5ac1975e7d38f6":{
      "scriptId":"u68"},
    "0bb5575834c24fcb98def4e9b9db19e9":{
      "scriptId":"u69"},
    "bbe5607df583420180263bcee8cd5ce2":{
      "scriptId":"u70"},
    "1478f3b5b8af49aa9d0c7008228ba3c8":{
      "scriptId":"u71"},
    "33a5b924ca4644f4ac31f4c3a36b121d":{
      "scriptId":"u72"},
    "696a4f3fad1d40518cc80d238295f2df":{
      "scriptId":"u73"},
    "3afc86b351454e79a92cadaa6faaa7ed":{
      "scriptId":"u74",
      "a21f855c285546afbe17b18ce85b3115":{
        "scriptId":"u75"},
      "949de136652e4587aaa28f6f15834e0c":{
        "scriptId":"u76"},
      "531b5bd5969249cabd327dee67defa54":{
        "scriptId":"u77"},
      "65888fe13bce4478a562495d426b9bc3":{
        "scriptId":"u78"},
      "0e76207fdbfe4764916e241645779d7a":{
        "scriptId":"u79"},
      "43b3baab91a245fa8c997f6b3b351b5e":{
        "scriptId":"u80"},
      "c44cddef4fba4676831e174309a3584a":{
        "scriptId":"u81"},
      "69cab1e7e91d4a2fa544dee179da730e":{
        "scriptId":"u82"},
      "20f4668cdfbf4c429ea0623b4820e6c8":{
        "scriptId":"u83"},
      "fbbf3217aa1d44e8a76d1f8af2b3978d":{
        "scriptId":"u84"},
      "21d3654616324d5d81e4d55d0ca8423b":{
        "scriptId":"u85"},
      "5f38062c4ab846cba118e63217fbb521":{
        "scriptId":"u86"},
      "9b171cf7f062487e9fda983e4ba64ca2":{
        "scriptId":"u87"}}}});