$axure.loadCurrentPage({
  "url":"消息详情页.html",
  "generationDate":new Date(1448888328634.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"47f380fadba04d99bab8e45750b09a96",
    "type":"Axure:Page",
    "name":"消息详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5c5fccd42de24bd2bd21e99488018bb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":10},
            "size":{
              "width":420,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2e3fba17b124d7d8fe1f4b2cc4cda86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":10},
                "size":{
                  "width":420,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"a2a42c065abf4c2caf92967413520770",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF029CDD},
            "location":{
              "x":180,
              "y":33},
            "size":{
              "width":420,
              "height":64},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de7ebcfc9f6148e88e15fa8c2e428279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF029CDD},
                "location":{
                  "x":180,
                  "y":33},
                "size":{
                  "width":420,
                  "height":64},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"12240c8ee50f486289a4b524688e3d8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":201,
              "y":51},
            "size":{
              "width":22,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bbd043e46724889acbbd8a13cc9d604",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":51},
                "size":{
                  "width":22,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df1cbb1fa4d24a2f85b56d6ba0ccc007",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":375,
              "y":59},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc465ddafe94dc6acbc9da2c8c7d5a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":375,
                  "y":59},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e49b536921ce4ff59345f6a23a0ef9eb",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":96},
            "size":{
              "width":420,
              "height":655}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["364d1936bd54421886e9794dd9f889a9"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If area of 移动 未接触 area of 刷新)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["364d1936bd54421886e9794dd9f889a9"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["4ce5ec520ae84db4b268177c941d0428"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 到 (0,-60) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["364d1936bd54421886e9794dd9f889a9"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-60",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"202532e47072461bb79f69b6a2b10719",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"364d1936bd54421886e9794dd9f889a9",
                  "label":"移动",
                  "parentDynamicPanel":"e49b536921ce4ff59345f6a23a0ef9eb",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-60},
                    "size":{
                      "width":420,
                      "height":1100}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"80c2f37a037e46bab55badcf75d377d1",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"fe3783fd231e4a8181c0e11f801fc6ef",
                          "label":"",
                          "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":17,
                              "y":80},
                            "size":{
                              "width":161,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b5ca17d173cc4626ba7faf1a9826d938",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":17,
                                  "y":80},
                                "size":{
                                  "width":161,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"527bc88521c347b8be01bd1fe5cd3229",
                          "label":"",
                          "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF797979,
                              "opacity":1},
                            "location":{
                              "x":16,
                              "y":109},
                            "size":{
                              "width":162,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"480f090b1ca94fdebd8e32a6b80dab33",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"14px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF797979,
                                  "opacity":1},
                                "location":{
                                  "x":16,
                                  "y":109},
                                "size":{
                                  "width":162,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"2f8755a6e8844573b8b878c4498eaa17",
                          "label":"",
                          "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":16,
                              "y":148},
                            "size":{
                              "width":384,
                              "height":172}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"bf9d48ddce0e4797afa811c04ed3478f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":16,
                                  "y":148},
                                "size":{
                                  "width":384,
                                  "height":172}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"a46659da9ca24d6d89a3c80a2c2653dc",
                          "label":"",
                          "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF6B6B6B,
                              "opacity":1},
                            "size":{
                              "width":420,
                              "height":60},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b11f9bea40da48b98569d4530b1202a1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"364d1936bd54421886e9794dd9f889a9",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF6B6B6B,
                                  "opacity":1},
                                "size":{
                                  "width":420,
                                  "height":60},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页-跟团游/u57.png"}}]}]},
{
                  "id":"4ce5ec520ae84db4b268177c941d0428",
                  "label":"刷新",
                  "parentDynamicPanel":"e49b536921ce4ff59345f6a23a0ef9eb",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":180,
                      "y":-100},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"b55c7d2ee7b8421f90cc1ffeecf60cac",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[]}]}]}]},
{
          "id":"7ee11fa1c5db454cade1ef70acde0e41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":180,
              "y":700},
            "size":{
              "width":420,
              "height":51},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19ca6c2aa852483089ddc375e40fe724",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":180,
                  "y":700},
                "size":{
                  "width":420,
                  "height":51},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u68.png"}},
{
          "id":"e39a83f25621401db8c3026cd640e22a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":388,
              "y":710},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58bb1e75842b454bada0dcf4067a558c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":388,
                  "y":710},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u70.png"}},
{
          "id":"c2e43014250549d2b17c98b429212f7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":493,
              "y":710},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af31209728784476b595e68377987d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":493,
                  "y":710},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u70.png"}},
{
          "id":"9056c5c20cbb4d16b0df2068918910ba",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":51}},
          "adaptiveStyles":{
},
          "masterId":"24ee36a07ae6402996d787d05dbe2333"},
{
          "id":"bb9fc70220f44961b37617eb32e42750",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":536,
              "y":46},
            "size":{
              "width":47,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62fecf3685ab4ccba49e332cb0410dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":536,
                  "y":46},
                "size":{
                  "width":47,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-跟团游/u7.png"}}]}},
  "masters":{
    "24ee36a07ae6402996d787d05dbe2333":{
      "packageId":"24ee36a07ae6402996d787d05dbe2333",
      "type":"Axure:Master",
      "name":"返回",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8a8660bc8f04408a89ed1f262f385543",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":22,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"60071eeef6464733864d3bee00e4500d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":22,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "5c5fccd42de24bd2bd21e99488018bb9":{
      "scriptId":"u0"},
    "d2e3fba17b124d7d8fe1f4b2cc4cda86":{
      "scriptId":"u1"},
    "a2a42c065abf4c2caf92967413520770":{
      "scriptId":"u2"},
    "de7ebcfc9f6148e88e15fa8c2e428279":{
      "scriptId":"u3"},
    "12240c8ee50f486289a4b524688e3d8c":{
      "scriptId":"u4"},
    "8bbd043e46724889acbbd8a13cc9d604":{
      "scriptId":"u5"},
    "df1cbb1fa4d24a2f85b56d6ba0ccc007":{
      "scriptId":"u6"},
    "adc465ddafe94dc6acbc9da2c8c7d5a4":{
      "scriptId":"u7"},
    "e49b536921ce4ff59345f6a23a0ef9eb":{
      "scriptId":"u8"},
    "364d1936bd54421886e9794dd9f889a9":{
      "scriptId":"u9"},
    "fe3783fd231e4a8181c0e11f801fc6ef":{
      "scriptId":"u10"},
    "b5ca17d173cc4626ba7faf1a9826d938":{
      "scriptId":"u11"},
    "527bc88521c347b8be01bd1fe5cd3229":{
      "scriptId":"u12"},
    "480f090b1ca94fdebd8e32a6b80dab33":{
      "scriptId":"u13"},
    "2f8755a6e8844573b8b878c4498eaa17":{
      "scriptId":"u14"},
    "bf9d48ddce0e4797afa811c04ed3478f":{
      "scriptId":"u15"},
    "a46659da9ca24d6d89a3c80a2c2653dc":{
      "scriptId":"u16"},
    "b11f9bea40da48b98569d4530b1202a1":{
      "scriptId":"u17"},
    "4ce5ec520ae84db4b268177c941d0428":{
      "scriptId":"u18"},
    "7ee11fa1c5db454cade1ef70acde0e41":{
      "scriptId":"u19"},
    "19ca6c2aa852483089ddc375e40fe724":{
      "scriptId":"u20"},
    "e39a83f25621401db8c3026cd640e22a":{
      "scriptId":"u21"},
    "58bb1e75842b454bada0dcf4067a558c":{
      "scriptId":"u22"},
    "c2e43014250549d2b17c98b429212f7e":{
      "scriptId":"u23"},
    "af31209728784476b595e68377987d35":{
      "scriptId":"u24"},
    "9056c5c20cbb4d16b0df2068918910ba":{
      "scriptId":"u25",
      "8a8660bc8f04408a89ed1f262f385543":{
        "scriptId":"u26"},
      "60071eeef6464733864d3bee00e4500d":{
        "scriptId":"u27"}},
    "bb9fc70220f44961b37617eb32e42750":{
      "scriptId":"u28"},
    "62fecf3685ab4ccba49e332cb0410dfb":{
      "scriptId":"u29"}}});