$axure.loadCurrentPage({
  "url":"目录页.html",
  "generationDate":new Date(1427081178122.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b9f97efdd83b42eb830acfb6ad17bb43",
    "type":"Axure:Page",
    "name":"目录页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f1442939bab14168bdeecfe7ad446e2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFEEEEEE},
            "location":{
              "x":275,
              "y":49},
            "size":{
              "width":1145,
              "height":60},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fe35977d25944a3a04d33fd8b573170",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFEEEEEE},
                "location":{
                  "x":275,
                  "y":49},
                "size":{
                  "width":1145,
                  "height":60},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/目录页/u0.png"}},
{
          "id":"6a96cfd3577b442880783c17578470a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF222222},
            "size":{
              "width":1680,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"262c3b98e44b4c17ad29bd3fc0df9b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF222222},
                "size":{
                  "width":1680,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/目录页/u2.png"}},
{
          "id":"9105bbcc9a194de1aba81c44ee268572",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":275,
              "y":17},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a09d80fa68884e2eab717a23d21039a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":275,
                  "y":17},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"126308834a4741fca071373b6d7c910a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":447,
              "y":17},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dd643b1d473439292a5367730691ce6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":447,
                  "y":17},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"daacc41010de430ab22c63f3ea8f87b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":531,
              "y":17},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dad14d3034f74fd7b7a611671b760c6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":531,
                  "y":17},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"fce05f96aa1b4ef793ebfa27768c677c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":631,
              "y":17},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73b33b848f8e4a28862dd20f54044b7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":631,
                  "y":17},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 热门赛事列表页",
                      "target":{
                        "targetType":"page",
                        "url":"热门赛事列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"847c756e4ac847c9a3a84be48782ead4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":130},
            "size":{
              "width":1145,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/目录页/u12_line.png"}},
{
          "id":"fbf19f66755d4a089de1189bf8fa4cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":161},
            "size":{
              "width":43,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f10cd122b25f41e0836eaff728070709",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":161},
                "size":{
                  "width":43,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f1442939bab14168bdeecfe7ad446e2b":{
      "scriptId":"u0"},
    "7fe35977d25944a3a04d33fd8b573170":{
      "scriptId":"u1"},
    "6a96cfd3577b442880783c17578470a7":{
      "scriptId":"u2"},
    "262c3b98e44b4c17ad29bd3fc0df9b5f":{
      "scriptId":"u3"},
    "9105bbcc9a194de1aba81c44ee268572":{
      "scriptId":"u4"},
    "a09d80fa68884e2eab717a23d21039a5":{
      "scriptId":"u5"},
    "126308834a4741fca071373b6d7c910a":{
      "scriptId":"u6"},
    "9dd643b1d473439292a5367730691ce6":{
      "scriptId":"u7"},
    "daacc41010de430ab22c63f3ea8f87b4":{
      "scriptId":"u8"},
    "dad14d3034f74fd7b7a611671b760c6a":{
      "scriptId":"u9"},
    "fce05f96aa1b4ef793ebfa27768c677c":{
      "scriptId":"u10"},
    "73b33b848f8e4a28862dd20f54044b7e":{
      "scriptId":"u11"},
    "847c756e4ac847c9a3a84be48782ead4":{
      "scriptId":"u12"},
    "fbf19f66755d4a089de1189bf8fa4cae":{
      "scriptId":"u13"},
    "f10cd122b25f41e0836eaff728070709":{
      "scriptId":"u14"}}});