$axure.loadCurrentPage({
  "url":"选择旅客.html",
  "generationDate":new Date(1448888324680.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3ea1e41847e74bac9e88dba852bea8df",
    "type":"Axure:Page",
    "name":"选择旅客",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ea065f284ba342069d9c5856535530e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":10},
            "size":{
              "width":420,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61ac9afe39e94423a00d3baea3cc9dc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":10},
                "size":{
                  "width":420,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"075b2dd59869472d9c190346767b54a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF029CDD},
            "location":{
              "x":180,
              "y":33},
            "size":{
              "width":420,
              "height":64},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f980f2704b254104bfca2f7fcec51147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF029CDD},
                "location":{
                  "x":180,
                  "y":33},
                "size":{
                  "width":420,
                  "height":64},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"d812a30a794640fb92ddbec689a72039",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":201,
              "y":51},
            "size":{
              "width":22,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e654e849116d4af39bf81938d6cb7369",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":51},
                "size":{
                  "width":22,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d22afcad4b7b4d618347ea65f62a71fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":57},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddd56781481044d6a616acad9366ed93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":57},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4eb89ccf21a4f6eaa299d7e4767699b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":96},
            "size":{
              "width":420,
              "height":655}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["2abefe830738460fa71038ffffd765ba"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If area of 移动 未接触 area of 刷新)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2abefe830738460fa71038ffffd765ba"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["4cd8441eed9d4b06b972805ef2f2c136"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 到 (0,-60) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["2abefe830738460fa71038ffffd765ba"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-60",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1cabb09a84e34b9c807097eea6ec1149",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2abefe830738460fa71038ffffd765ba",
                  "label":"移动",
                  "parentDynamicPanel":"b4eb89ccf21a4f6eaa299d7e4767699b",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-60},
                    "size":{
                      "width":420,
                      "height":800}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"59fadf34a15449cfaa24761f5e55fb3e",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"5c561d31b9d74c2a895f190b8a057ed9",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":111},
                            "size":{
                              "width":419,
                              "height":219},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"da54a234a22b427b9001e1e41fb5d974",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":111},
                                "size":{
                                  "width":419,
                                  "height":219},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u10.png"}},
{
                          "id":"fde26d290ab34883bac3c379bfe9282f",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":60},
                            "size":{
                              "width":210,
                              "height":40},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"97927b229935443ea8d3114aa6a99586",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":60},
                                "size":{
                                  "width":210,
                                  "height":40},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u12.png"}},
{
                          "id":"c091a6a397e24360b8ae9ba335ebfc40",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF5F5F5},
                            "location":{
                              "x":27,
                              "y":70},
                            "size":{
                              "width":40,
                              "height":20},
                            "borderWidth":"-1",
                            "cornerRadiusTopLeft":"2"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"57078987c85a4218b3e2cd7f401992fc",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF5F5F5},
                                "location":{
                                  "x":27,
                                  "y":70},
                                "size":{
                                  "width":40,
                                  "height":20},
                                "borderWidth":"-1",
                                "cornerRadiusTopLeft":"2"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u14.png"}},
{
                          "id":"d88ff6df8ce6405d9b17b2c33b50d59d",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":85,
                              "y":72},
                            "size":{
                              "width":38,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"52b61860d7754bf4ba99b6e62cfbe51a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":85,
                                  "y":72},
                                "size":{
                                  "width":38,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"d91a04d8bce34147b2d2b566c5eb3161",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":209,
                              "y":60},
                            "size":{
                              "width":210,
                              "height":40},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"4115b995ae2f486cb374e908dbafac17",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":209,
                                  "y":60},
                                "size":{
                                  "width":210,
                                  "height":40},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u12.png"}},
{
                          "id":"0608da55719648f9b72b7665df9839ac",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFF95DAF2},
                            "location":{
                              "x":240,
                              "y":70},
                            "size":{
                              "width":40,
                              "height":20},
                            "borderWidth":"-1",
                            "cornerRadiusTopLeft":"2"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"15f6bb942dd742759d09a915fedbabee",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFF95DAF2},
                                "location":{
                                  "x":240,
                                  "y":70},
                                "size":{
                                  "width":40,
                                  "height":20},
                                "borderWidth":"-1",
                                "cornerRadiusTopLeft":"2"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u20.png"}},
{
                          "id":"5c8f22b9d198480c9019ccec3d0ede3b",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":580,
                              "y":306},
                            "size":{
                              "width":530,
                              "height":404}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"78122775862c4cc29665cbc5ed1dfb46",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":580,
                                  "y":306},
                                "size":{
                                  "width":530,
                                  "height":404}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u22.png"}},
{
                          "id":"0f5a2725854f48e1bd82075a6773d0cb",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontWeight":"700",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFCC9933,
                              "opacity":1},
                            "location":{
                              "x":298,
                              "y":72},
                            "size":{
                              "width":12,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9718dbb52ffb49d68a95bc7b20803e54",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Arial Negreta', 'Arial'",
                                "fontWeight":"700",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFCC9933,
                                  "opacity":1},
                                "location":{
                                  "x":298,
                                  "y":72},
                                "size":{
                                  "width":12,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"0df57fa7f48c460f83beae123009ebee",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":320,
                              "y":72},
                            "size":{
                              "width":27,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9d7c3d74164a4c048152eb9f66f62506",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":320,
                                  "y":72},
                                "size":{
                                  "width":27,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"c8124fa927e24f14a94dfb522462626b",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":17,
                              "y":126},
                            "size":{
                              "width":396,
                              "height":31}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"53c8313223ba4e9a8c10a9a2b6ac2396",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":17,
                                  "y":126},
                                "size":{
                                  "width":396,
                                  "height":31}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u28.png"}},
{
                          "id":"2a8e172284ce4a01815336fd3e3fc9c0",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"checkbox",
                          "styleType":"checkbox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":23,
                              "y":194},
                            "size":{
                              "width":30,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7e3de3bf9b5243e99b6ace89746afdc2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":23,
                                  "y":194},
                                "size":{
                                  "width":30,
                                  "height":16}},
                              "adaptiveStyles":{
}}]},
{
                          "id":"a6ef0d46ecc2463bb2d2437aa693943b",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":63,
                              "y":182},
                            "size":{
                              "width":49,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8f5fd2674daa49a9a664bdc6bd0de8a7",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":63,
                                  "y":182},
                                "size":{
                                  "width":49,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"fe1b9bab3be646f4a4f05939dc523482",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFAEAEAE,
                              "opacity":1},
                            "location":{
                              "x":63,
                              "y":211},
                            "size":{
                              "width":168,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6bc63eeb6dc9435191c8aebaef709c1e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFAEAEAE,
                                  "opacity":1},
                                "location":{
                                  "x":63,
                                  "y":211},
                                "size":{
                                  "width":168,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"aafc423195554e28aa8bf17cb081d280",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":360,
                              "y":190},
                            "size":{
                              "width":31,
                              "height":33}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a87805b891b34b6bb679520a9f44f479",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":360,
                                  "y":190},
                                "size":{
                                  "width":31,
                                  "height":33}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 编辑旅客信息",
                                      "target":{
                                        "targetType":"page",
                                        "url":"编辑旅客信息.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/选择旅客/u36.png"}},
{
                          "id":"081acdd1c414408d916856c75187ca49",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":21,
                              "y":167},
                            "size":{
                              "width":398,
                              "height":10},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/选择旅客/u38_line.png"}},
{
                          "id":"23e8914a8a414fb98737389be576daee",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"horizontalLine",
                          "styleType":"horizontalLine",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":21,
                              "y":237},
                            "size":{
                              "width":398,
                              "height":10},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9}},
                          "adaptiveStyles":{
},
                          "images":{
                            "start~":"resources/images/transparent.gif",
                            "end~":"resources/images/transparent.gif",
                            "line~":"images/选择旅客/u38_line.png"}},
{
                          "id":"c22797b3f6f148e8916a42bcddc1658a",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"checkbox",
                          "styleType":"checkbox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":23,
                              "y":269},
                            "size":{
                              "width":30,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a76ca4ee95ad4e169ae894159a0b4bdb",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":23,
                                  "y":269},
                                "size":{
                                  "width":30,
                                  "height":16}},
                              "adaptiveStyles":{
}}]},
{
                          "id":"fe80b0fccba74e8d844d43e0ab7b6ede",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontSize":"16px",
                            "location":{
                              "x":63,
                              "y":257},
                            "size":{
                              "width":49,
                              "height":19}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5202733a631a4d51ba4c19b098a02571",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"16px",
                                "location":{
                                  "x":63,
                                  "y":257},
                                "size":{
                                  "width":49,
                                  "height":19}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"da14717d416742d5a45d275bc57abff7",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFAEAEAE,
                              "opacity":1},
                            "location":{
                              "x":63,
                              "y":286},
                            "size":{
                              "width":168,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f1911973ba7b4594bc1c17a006fee9d4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFAEAEAE,
                                  "opacity":1},
                                "location":{
                                  "x":63,
                                  "y":286},
                                "size":{
                                  "width":168,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"0b905d75c71b4c4ca34d1a7aaab1d1d4",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":360,
                              "y":265},
                            "size":{
                              "width":31,
                              "height":33}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"59bec5eaf1864530a83ad9114a6a6ccb",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":360,
                                  "y":265},
                                "size":{
                                  "width":31,
                                  "height":33}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/选择旅客/u36.png"}},
{
                          "id":"005b0a0fa7c84bd1b8fa3aadfc483b31",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF6B6B6B,
                              "opacity":1},
                            "size":{
                              "width":419,
                              "height":60},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0d59f44cc4bf459c82e49371fd28f3e1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF6B6B6B,
                                  "opacity":1},
                                "size":{
                                  "width":419,
                                  "height":60},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/订单购买流程（选择日期、人数）/u24.png"}},
{
                          "id":"0b27e878b2f64d92bed61c9c661cd4cd",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":359,
                              "y":190},
                            "size":{
                              "width":4,
                              "height":33}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f99db1f785184642bd80308e97cd5dee",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":359,
                                  "y":190},
                                "size":{
                                  "width":4,
                                  "height":33}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"4e237d07fcf140df953ce15780ee1358",
                          "label":"",
                          "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":360,
                              "y":265},
                            "size":{
                              "width":31,
                              "height":33}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f105351f550a4fd6ba1387302e5456a2",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"2abefe830738460fa71038ffffd765ba",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":360,
                                  "y":265},
                                "size":{
                                  "width":31,
                                  "height":33}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 编辑旅客信息",
                                      "target":{
                                        "targetType":"page",
                                        "url":"编辑旅客信息.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/选择旅客/u36.png"}}]}]},
{
                  "id":"4cd8441eed9d4b06b972805ef2f2c136",
                  "label":"刷新",
                  "parentDynamicPanel":"b4eb89ccf21a4f6eaa299d7e4767699b",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":180,
                      "y":-100},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"945b56c6e200422fbe6432b21030a16a",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[]}]}]}]},
{
          "id":"4e150c2576e5434e884d0da1453fb21b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":51}},
          "adaptiveStyles":{
},
          "masterId":"24ee36a07ae6402996d787d05dbe2333"},
{
          "id":"bf7234b1723f4d419b79edf4223a899b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":180,
              "y":710},
            "size":{
              "width":420,
              "height":41},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feff93f64ff1400a9e41f91580353339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":180,
                  "y":710},
                "size":{
                  "width":420,
                  "height":41},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/选择旅客/u58.png"}},
{
          "id":"9fa26a3ba4ab4e20864b1c164565d2f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":536,
              "y":46},
            "size":{
              "width":47,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeedda312a5942b0a270f4104e81a900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":536,
                  "y":46},
                "size":{
                  "width":47,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-跟团游/u7.png"}}]}},
  "masters":{
    "24ee36a07ae6402996d787d05dbe2333":{
      "packageId":"24ee36a07ae6402996d787d05dbe2333",
      "type":"Axure:Master",
      "name":"返回",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8a8660bc8f04408a89ed1f262f385543",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":22,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"60071eeef6464733864d3bee00e4500d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":22,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "ea065f284ba342069d9c5856535530e4":{
      "scriptId":"u0"},
    "61ac9afe39e94423a00d3baea3cc9dc3":{
      "scriptId":"u1"},
    "075b2dd59869472d9c190346767b54a0":{
      "scriptId":"u2"},
    "f980f2704b254104bfca2f7fcec51147":{
      "scriptId":"u3"},
    "d812a30a794640fb92ddbec689a72039":{
      "scriptId":"u4"},
    "e654e849116d4af39bf81938d6cb7369":{
      "scriptId":"u5"},
    "d22afcad4b7b4d618347ea65f62a71fb":{
      "scriptId":"u6"},
    "ddd56781481044d6a616acad9366ed93":{
      "scriptId":"u7"},
    "b4eb89ccf21a4f6eaa299d7e4767699b":{
      "scriptId":"u8"},
    "2abefe830738460fa71038ffffd765ba":{
      "scriptId":"u9"},
    "5c561d31b9d74c2a895f190b8a057ed9":{
      "scriptId":"u10"},
    "da54a234a22b427b9001e1e41fb5d974":{
      "scriptId":"u11"},
    "fde26d290ab34883bac3c379bfe9282f":{
      "scriptId":"u12"},
    "97927b229935443ea8d3114aa6a99586":{
      "scriptId":"u13"},
    "c091a6a397e24360b8ae9ba335ebfc40":{
      "scriptId":"u14"},
    "57078987c85a4218b3e2cd7f401992fc":{
      "scriptId":"u15"},
    "d88ff6df8ce6405d9b17b2c33b50d59d":{
      "scriptId":"u16"},
    "52b61860d7754bf4ba99b6e62cfbe51a":{
      "scriptId":"u17"},
    "d91a04d8bce34147b2d2b566c5eb3161":{
      "scriptId":"u18"},
    "4115b995ae2f486cb374e908dbafac17":{
      "scriptId":"u19"},
    "0608da55719648f9b72b7665df9839ac":{
      "scriptId":"u20"},
    "15f6bb942dd742759d09a915fedbabee":{
      "scriptId":"u21"},
    "5c8f22b9d198480c9019ccec3d0ede3b":{
      "scriptId":"u22"},
    "78122775862c4cc29665cbc5ed1dfb46":{
      "scriptId":"u23"},
    "0f5a2725854f48e1bd82075a6773d0cb":{
      "scriptId":"u24"},
    "9718dbb52ffb49d68a95bc7b20803e54":{
      "scriptId":"u25"},
    "0df57fa7f48c460f83beae123009ebee":{
      "scriptId":"u26"},
    "9d7c3d74164a4c048152eb9f66f62506":{
      "scriptId":"u27"},
    "c8124fa927e24f14a94dfb522462626b":{
      "scriptId":"u28"},
    "53c8313223ba4e9a8c10a9a2b6ac2396":{
      "scriptId":"u29"},
    "2a8e172284ce4a01815336fd3e3fc9c0":{
      "scriptId":"u30"},
    "7e3de3bf9b5243e99b6ace89746afdc2":{
      "scriptId":"u31"},
    "a6ef0d46ecc2463bb2d2437aa693943b":{
      "scriptId":"u32"},
    "8f5fd2674daa49a9a664bdc6bd0de8a7":{
      "scriptId":"u33"},
    "fe1b9bab3be646f4a4f05939dc523482":{
      "scriptId":"u34"},
    "6bc63eeb6dc9435191c8aebaef709c1e":{
      "scriptId":"u35"},
    "aafc423195554e28aa8bf17cb081d280":{
      "scriptId":"u36"},
    "a87805b891b34b6bb679520a9f44f479":{
      "scriptId":"u37"},
    "081acdd1c414408d916856c75187ca49":{
      "scriptId":"u38"},
    "23e8914a8a414fb98737389be576daee":{
      "scriptId":"u39"},
    "c22797b3f6f148e8916a42bcddc1658a":{
      "scriptId":"u40"},
    "a76ca4ee95ad4e169ae894159a0b4bdb":{
      "scriptId":"u41"},
    "fe80b0fccba74e8d844d43e0ab7b6ede":{
      "scriptId":"u42"},
    "5202733a631a4d51ba4c19b098a02571":{
      "scriptId":"u43"},
    "da14717d416742d5a45d275bc57abff7":{
      "scriptId":"u44"},
    "f1911973ba7b4594bc1c17a006fee9d4":{
      "scriptId":"u45"},
    "0b905d75c71b4c4ca34d1a7aaab1d1d4":{
      "scriptId":"u46"},
    "59bec5eaf1864530a83ad9114a6a6ccb":{
      "scriptId":"u47"},
    "005b0a0fa7c84bd1b8fa3aadfc483b31":{
      "scriptId":"u48"},
    "0d59f44cc4bf459c82e49371fd28f3e1":{
      "scriptId":"u49"},
    "0b27e878b2f64d92bed61c9c661cd4cd":{
      "scriptId":"u50"},
    "f99db1f785184642bd80308e97cd5dee":{
      "scriptId":"u51"},
    "4e237d07fcf140df953ce15780ee1358":{
      "scriptId":"u52"},
    "f105351f550a4fd6ba1387302e5456a2":{
      "scriptId":"u53"},
    "4cd8441eed9d4b06b972805ef2f2c136":{
      "scriptId":"u54"},
    "4e150c2576e5434e884d0da1453fb21b":{
      "scriptId":"u55",
      "8a8660bc8f04408a89ed1f262f385543":{
        "scriptId":"u56"},
      "60071eeef6464733864d3bee00e4500d":{
        "scriptId":"u57"}},
    "bf7234b1723f4d419b79edf4223a899b":{
      "scriptId":"u58"},
    "feff93f64ff1400a9e41f91580353339":{
      "scriptId":"u59"},
    "9fa26a3ba4ab4e20864b1c164565d2f7":{
      "scriptId":"u60"},
    "eeedda312a5942b0a270f4104e81a900":{
      "scriptId":"u61"}}});