$axure.loadCurrentPage({
  "url":"____互动管理-讨论圈管理.html",
  "generationDate":new Date(1403249363060.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ccb161ed41fd4da28dcaf0e37c7e13bf",
    "type":"Axure:Page",
    "name":"****互动管理-讨论圈管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25b630cb08c04f6aa6a892d642334872",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"ff32ee69a5714c5d8edb018882295e52"},
{
          "id":"864001b28df3470795dd793c63f9b0df",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90}},
          "adaptiveStyles":{
},
          "masterId":"c815ba5abb4f43939c361e68685350d9"},
{
          "id":"caca4f7a8cf847a194268ed7ce626d1e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":650}},
          "adaptiveStyles":{
},
          "masterId":"64dfa9a83e704e3baf711a14157067f5"},
{
          "id":"4d6d551443634650a578295415e94784",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"64dfa9a83e704e3baf711a14157067f5"},
{
          "id":"b36163aa160c4dc89b78685dc934a3bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":200,
              "y":90},
            "size":{
              "width":169,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ea9fd4ad8441309f40442cbbde4e4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":169,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c7ddaa6eaf1a4834b2a07cf3053b5ec5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":145},
            "size":{
              "width":1000,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单管理-订单列表/u68_line.png"}},
{
          "id":"a899e20cde164fb5b42f9ea8d4d67be9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":165},
            "size":{
              "width":1348,
              "height":718}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cf9c591d956497f959c91947aacd5a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":165},
                "size":{
                  "width":1348,
                  "height":718}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/____互动管理-讨论圈管理/u95.png"}}]}},
  "masters":{
    "ff32ee69a5714c5d8edb018882295e52":{
      "packageId":"ff32ee69a5714c5d8edb018882295e52",
      "type":"Axure:Master",
      "name":"公共导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"290ebc0dc7f846b9be2001eccf636f2f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":61},
              "size":{
                "width":1190,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFAEAEAE}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"85774be102bf47418e9f5dadd86016e3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":61},
                  "size":{
                    "width":1190,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFAEAEAE}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统首页/u1.png"}},
{
            "id":"cafb2aee0c714cdc9d953a986fbb3972",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":10},
              "size":{
                "width":150,
                "height":43},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFAEAEAE}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b2daa3c66d14c3a883879f71ba3faa1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":10},
                  "size":{
                    "width":150,
                    "height":43},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFAEAEAE}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统首页/u3.png"}},
{
            "id":"42517e95a6904675961de720039df4f8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":30},
              "size":{
                "width":1000,
                "height":30},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa44bc1fb9cb4298ac01109b34d86060",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":30},
                  "size":{
                    "width":1000,
                    "height":30},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统首页/u5.png"}},
{
            "id":"8de3663f158c47d6b0e79165e26cec75",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":285,
                "y":30},
              "size":{
                "width":95,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c00b1da7b3fc41a1b94bc74eaf6950b0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":285,
                    "y":30},
                  "size":{
                    "width":95,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 订单",
                        "target":{
                          "targetType":"page",
                          "url":"订单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u7.png"}},
{
            "id":"847989cd080f46b0aec6b0472202ed20",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":30},
              "size":{
                "width":96,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"22a3d32419d341de8d75a26de1000db3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":30},
                  "size":{
                    "width":96,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 商品",
                        "target":{
                          "targetType":"page",
                          "url":"商品.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u9.png"}},
{
            "id":"456481581083445d9e5f22946e6b6cf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":476,
                "y":30},
              "size":{
                "width":95,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2722e94b2d0245ceaf64b68219a4a261",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":476,
                    "y":30},
                  "size":{
                    "width":95,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 营销",
                        "target":{
                          "targetType":"page",
                          "url":"营销.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u7.png"}},
{
            "id":"ab972ad9d6f74ed1b7fd2ac6a6e49c19",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":571,
                "y":30},
              "size":{
                "width":95,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a77ac366f22d49e49727e374462adbf8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":571,
                    "y":30},
                  "size":{
                    "width":95,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 手机站",
                        "target":{
                          "targetType":"page",
                          "url":"手机站.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u7.png"}},
{
            "id":"734d204106e643e2a7669f8b8d9d4731",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":666,
                "y":30},
              "size":{
                "width":95,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"60a6fc263059454199256e18a4c94bb2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":666,
                    "y":30},
                  "size":{
                    "width":95,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 系统管理",
                        "target":{
                          "targetType":"page",
                          "url":"系统管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u7.png"}},
{
            "id":"aea4b80b262a4de896252f9d48e012e0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":190,
                "y":30},
              "size":{
                "width":95,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"333e4ee46e50464cb96c790dcfeafa55",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":190,
                    "y":30},
                  "size":{
                    "width":95,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 系统首页",
                        "target":{
                          "targetType":"page",
                          "url":"系统首页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u7.png"}},
{
            "id":"c0d41d04d1e24db0885e28382b97357a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":66,
                "y":68},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9389961a6d44465989c360b293811b7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":66,
                    "y":68},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8f0a3faa1339442eb4a61f0f44e99c1c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":200,
                "y":67},
              "size":{
                "width":314,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8779e8d4c49c4cd8b67c45c31adcbe44",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":200,
                    "y":67},
                  "size":{
                    "width":314,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"89eebae2f3664644b28be8c9153c96af",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":761,
                "y":30},
              "size":{
                "width":96,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"575110c9b496494b9f095ea5f80caf48",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":761,
                    "y":30},
                  "size":{
                    "width":96,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 推荐管理",
                        "target":{
                          "targetType":"page",
                          "url":"推荐管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u9.png"}},
{
            "id":"14cf8d11f58d44ff89b444de7b80a49a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":857,
                "y":30},
              "size":{
                "width":95,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f86adcf4dec54c95aee2407a86c9f195",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":857,
                    "y":30},
                  "size":{
                    "width":95,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":true,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://bh.ewt.cc",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://bh.ewt.cc",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/系统首页/u7.png"}},
{
            "id":"06a5ef31c51c41bdad22c421b52f28b5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":738,
                "y":67},
              "size":{
                "width":306,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c72ec58f71a44215956a01fe69b07dae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":738,
                    "y":67},
                  "size":{
                    "width":306,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "c815ba5abb4f43939c361e68685350d9":{
      "packageId":"c815ba5abb4f43939c361e68685350d9",
      "type":"Axure:Master",
      "name":"推荐管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"45faaa3109134fd29fae7b4d39fd68cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":40},
              "size":{
                "width":190,
                "height":330},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59fadb19bdc3475ebc168cbde47dac1a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":40},
                  "size":{
                    "width":190,
                    "height":330},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/推荐管理/u30.png"}},
{
            "id":"73b270766ca3444fa327c1f9751ed0e1",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "size":{
                "width":190,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"35f378d14095498cbfc64ab5196ca501",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "size":{
                    "width":190,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统首页/u73.png"}},
{
            "id":"bf4f97be68f943249e9c42e6daef9737",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":50},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"397325da80f543f1be895ac7ff549172",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":50},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-自动推荐管理",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-自动推荐管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8d1308fd4cd3466a9600045fc4c0a750",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":126},
              "size":{
                "width":66,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"30c18d2b7611490e997fe3fb12d08823",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":126},
                  "size":{
                    "width":66,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-频道页推荐",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-频道页推荐.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a9c8c1b8443844bf9f43db3b5729d504",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":152},
              "size":{
                "width":66,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1606928af2394d1ea385d639fd5dad7a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":152},
                  "size":{
                    "width":66,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-品牌页推荐",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-品牌页推荐.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bad99bf228a0453295665c07b0440226",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":102},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3c4311fa3f0b4775abca089b4155c634",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":102},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-首页推荐",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-首页推荐.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fdee126eb65146f99abeb317dfbb8cb8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":178},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d9cc942e2d1f43c6bbe4daa72be62184",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":178},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-关联推荐-销售排行榜",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-关联推荐-销售排行榜.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f118bce1f2b8433b8e792b72841aef9e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":410},
              "size":{
                "width":190,
                "height":330},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2f6c35381d7c44c9974ff78647695fd5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":410},
                  "size":{
                    "width":190,
                    "height":330},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/推荐管理/u30.png"}},
{
            "id":"c96a083eaab94b8784156ac90ab0e981",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "horizontalAlignment":"left",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":0,
                "y":370},
              "size":{
                "width":190,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fb33e41a10144358c8ce166028acbd9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "horizontalAlignment":"left",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":0,
                    "y":370},
                  "size":{
                    "width":190,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统首页/u73.png"}},
{
            "id":"e63290e73f404705bc984d3c08b3d1e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":420},
              "size":{
                "width":53,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b68439065c064e98a771525aefb9acfc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":420},
                  "size":{
                    "width":53,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 互动管理-评价列表",
                        "target":{
                          "targetType":"page",
                          "url":"互动管理-评价列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"09b3b8d4664f44a78352fcba69ed8a12",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":470},
              "size":{
                "width":96,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7797372f9aab48c5beeaba5510b2c7af",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":470},
                  "size":{
                    "width":96,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 ****互动管理-自定义评价/咨询",
                        "target":{
                          "targetType":"page",
                          "url":"____互动管理-自定义评价_咨询.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"38d8805ec7c44db39d012f6327abe2cc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":496},
              "size":{
                "width":53,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ab913f249494e88a834635a58ececfa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":496},
                  "size":{
                    "width":53,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 ****互动管理-商品预定",
                        "target":{
                          "targetType":"page",
                          "url":"____互动管理-商品预定.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6290d059addf4ddd8477f160ace126f4",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":446},
              "size":{
                "width":53,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c7c1089681c479486fdc4a3369f2245",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":446},
                  "size":{
                    "width":53,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 互动管理-咨询列表",
                        "target":{
                          "targetType":"page",
                          "url":"互动管理-咨询列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7e5bcd067dd94244a339e7866522a4cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":522},
              "size":{
                "width":53,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fd8cbef10f3d4aae93d040213815c7ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":522},
                  "size":{
                    "width":53,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 ****互动管理-举报管理",
                        "target":{
                          "targetType":"page",
                          "url":"____互动管理-举报管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"90fb662ab9f146febb18aeae1861d5a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":548},
              "size":{
                "width":53,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f8ba7f108ca04fbf9f9c644e9c9ead42",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":548},
                  "size":{
                    "width":53,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 ****互动管理-投诉管理",
                        "target":{
                          "targetType":"page",
                          "url":"____互动管理-投诉管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e56a8d2fb0484f0b86ad3a94389ef465",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":574},
              "size":{
                "width":66,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cb26296822be4e539ded7ecd07f0d6b6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":574},
                  "size":{
                    "width":66,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 ****互动管理-讨论圈管理",
                        "target":{
                          "targetType":"page",
                          "url":"____互动管理-讨论圈管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2b2a98b7702940e68e6fe36508996623",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":600},
              "size":{
                "width":53,
                "height":16},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"78f6bea1ad7a458bb2d642e92525820c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":600},
                  "size":{
                    "width":53,
                    "height":16},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFE4E4E4}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 ****互动管理-留言建议",
                        "target":{
                          "targetType":"page",
                          "url":"____互动管理-留言建议.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff99c73ae4004435ae6fe0c8cd92ca82",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":626},
              "size":{
                "width":105,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9594b99a48b649a9ac16863410d49a29",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":626},
                  "size":{
                    "width":105,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 互动管理-友情链接申请管理",
                        "target":{
                          "targetType":"page",
                          "url":"互动管理-友情链接申请管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5ab63e881b09490988e4b99e0d3aa6ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":204},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eacd537df0cf486aaa676df80f6f1c85",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":204},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-友情链接-图片推荐",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-友情链接-图片推荐.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dac0e162aae54759a2365550fa20ad90",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":230},
              "size":{
                "width":48,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bf92882fbd124156befb3011315b6813",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":230},
                  "size":{
                    "width":48,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-404页面-404内容",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-404页面-404内容.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"81d034bfa1234cf08900eaab107cc979",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":256},
              "size":{
                "width":48,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef4c44d228214f0cbc2663ab771f63d8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":256},
                  "size":{
                    "width":48,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-503页面-503内容",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-503页面-503内容.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"940d47e618334bf6bf5809632d96dd65",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":282},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6549f050a6984f49924ccd5f689f98df",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":282},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-网站地图",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-网站地图.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"43f6ad0df5144d41b7a4a0e3cfdbe563",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":308},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"10da916a0dc04ed3a22c7f1a715a4e41",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":308},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-专题管理",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-专题管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37b20c2daeaf4394a7f3cc1a901e4f72",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":652},
              "size":{
                "width":79,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f238a7c00608449bb521bfd615495994",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":652},
                  "size":{
                    "width":79,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 互动管理-商品浏览历史",
                        "target":{
                          "targetType":"page",
                          "url":"互动管理-商品浏览历史.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1cde682b88fb4638827a57e1cdd2e681",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":678},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3196c34ec8304a3399ce08e7b106b539",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":678},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 互动管理-收藏管理",
                        "target":{
                          "targetType":"page",
                          "url":"互动管理-收藏管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1d730ee9d34948aa977a69d4d0ca511f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":704},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f7bdd736b16c4396884c759966a562d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":704},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 互动管理-订阅管理",
                        "target":{
                          "targetType":"page",
                          "url":"互动管理-订阅管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e25ec83952df4eec9abaf9ce463f9c20",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":334},
              "size":{
                "width":66,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3200eabbebe44086a718e9aaa5fefe3b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":334},
                  "size":{
                    "width":66,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-供应商加盟-焦点推荐",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-供应商加盟-焦点推荐.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b3dcdd1b50ca4d59ba84c23b7273cc1a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":76},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"198b730695324146a08c3129b1e5de72",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":76},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 页面内容管理-页面管理",
                        "target":{
                          "targetType":"page",
                          "url":"页面内容管理-页面管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "64dfa9a83e704e3baf711a14157067f5":{
      "packageId":"64dfa9a83e704e3baf711a14157067f5",
      "type":"Axure:Master",
      "name":"导航标识",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"e4996488ed8b430bb0cc8e2cc4304738",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x75FFFF66},
              "location":{
                "x":190,
                "y":30},
              "size":{
                "width":95,
                "height":30},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0ab1a2c40f714d4da951cce312690e4c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x75FFFF66},
                  "location":{
                    "x":190,
                    "y":30},
                  "size":{
                    "width":95,
                    "height":30},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/系统首页/u30.png",
              "normal~":"images/系统首页/u30.png"}}]}}},
  "objectPaths":{
    "25b630cb08c04f6aa6a892d642334872":{
      "scriptId":"u0",
      "290ebc0dc7f846b9be2001eccf636f2f":{
        "scriptId":"u1"},
      "85774be102bf47418e9f5dadd86016e3":{
        "scriptId":"u2"},
      "cafb2aee0c714cdc9d953a986fbb3972":{
        "scriptId":"u3"},
      "9b2daa3c66d14c3a883879f71ba3faa1":{
        "scriptId":"u4"},
      "42517e95a6904675961de720039df4f8":{
        "scriptId":"u5"},
      "fa44bc1fb9cb4298ac01109b34d86060":{
        "scriptId":"u6"},
      "8de3663f158c47d6b0e79165e26cec75":{
        "scriptId":"u7"},
      "c00b1da7b3fc41a1b94bc74eaf6950b0":{
        "scriptId":"u8"},
      "847989cd080f46b0aec6b0472202ed20":{
        "scriptId":"u9"},
      "22a3d32419d341de8d75a26de1000db3":{
        "scriptId":"u10"},
      "456481581083445d9e5f22946e6b6cf5":{
        "scriptId":"u11"},
      "2722e94b2d0245ceaf64b68219a4a261":{
        "scriptId":"u12"},
      "ab972ad9d6f74ed1b7fd2ac6a6e49c19":{
        "scriptId":"u13"},
      "a77ac366f22d49e49727e374462adbf8":{
        "scriptId":"u14"},
      "734d204106e643e2a7669f8b8d9d4731":{
        "scriptId":"u15"},
      "60a6fc263059454199256e18a4c94bb2":{
        "scriptId":"u16"},
      "aea4b80b262a4de896252f9d48e012e0":{
        "scriptId":"u17"},
      "333e4ee46e50464cb96c790dcfeafa55":{
        "scriptId":"u18"},
      "c0d41d04d1e24db0885e28382b97357a":{
        "scriptId":"u19"},
      "d9389961a6d44465989c360b293811b7":{
        "scriptId":"u20"},
      "8f0a3faa1339442eb4a61f0f44e99c1c":{
        "scriptId":"u21"},
      "8779e8d4c49c4cd8b67c45c31adcbe44":{
        "scriptId":"u22"},
      "89eebae2f3664644b28be8c9153c96af":{
        "scriptId":"u23"},
      "575110c9b496494b9f095ea5f80caf48":{
        "scriptId":"u24"},
      "14cf8d11f58d44ff89b444de7b80a49a":{
        "scriptId":"u25"},
      "f86adcf4dec54c95aee2407a86c9f195":{
        "scriptId":"u26"},
      "06a5ef31c51c41bdad22c421b52f28b5":{
        "scriptId":"u27"},
      "c72ec58f71a44215956a01fe69b07dae":{
        "scriptId":"u28"}},
    "864001b28df3470795dd793c63f9b0df":{
      "scriptId":"u29",
      "45faaa3109134fd29fae7b4d39fd68cd":{
        "scriptId":"u30"},
      "59fadb19bdc3475ebc168cbde47dac1a":{
        "scriptId":"u31"},
      "73b270766ca3444fa327c1f9751ed0e1":{
        "scriptId":"u32"},
      "35f378d14095498cbfc64ab5196ca501":{
        "scriptId":"u33"},
      "bf4f97be68f943249e9c42e6daef9737":{
        "scriptId":"u34"},
      "397325da80f543f1be895ac7ff549172":{
        "scriptId":"u35"},
      "8d1308fd4cd3466a9600045fc4c0a750":{
        "scriptId":"u36"},
      "30c18d2b7611490e997fe3fb12d08823":{
        "scriptId":"u37"},
      "a9c8c1b8443844bf9f43db3b5729d504":{
        "scriptId":"u38"},
      "1606928af2394d1ea385d639fd5dad7a":{
        "scriptId":"u39"},
      "bad99bf228a0453295665c07b0440226":{
        "scriptId":"u40"},
      "3c4311fa3f0b4775abca089b4155c634":{
        "scriptId":"u41"},
      "fdee126eb65146f99abeb317dfbb8cb8":{
        "scriptId":"u42"},
      "d9cc942e2d1f43c6bbe4daa72be62184":{
        "scriptId":"u43"},
      "f118bce1f2b8433b8e792b72841aef9e":{
        "scriptId":"u44"},
      "2f6c35381d7c44c9974ff78647695fd5":{
        "scriptId":"u45"},
      "c96a083eaab94b8784156ac90ab0e981":{
        "scriptId":"u46"},
      "5fb33e41a10144358c8ce166028acbd9":{
        "scriptId":"u47"},
      "e63290e73f404705bc984d3c08b3d1e3":{
        "scriptId":"u48"},
      "b68439065c064e98a771525aefb9acfc":{
        "scriptId":"u49"},
      "09b3b8d4664f44a78352fcba69ed8a12":{
        "scriptId":"u50"},
      "7797372f9aab48c5beeaba5510b2c7af":{
        "scriptId":"u51"},
      "38d8805ec7c44db39d012f6327abe2cc":{
        "scriptId":"u52"},
      "3ab913f249494e88a834635a58ececfa":{
        "scriptId":"u53"},
      "6290d059addf4ddd8477f160ace126f4":{
        "scriptId":"u54"},
      "7c7c1089681c479486fdc4a3369f2245":{
        "scriptId":"u55"},
      "7e5bcd067dd94244a339e7866522a4cd":{
        "scriptId":"u56"},
      "fd8cbef10f3d4aae93d040213815c7ed":{
        "scriptId":"u57"},
      "90fb662ab9f146febb18aeae1861d5a5":{
        "scriptId":"u58"},
      "f8ba7f108ca04fbf9f9c644e9c9ead42":{
        "scriptId":"u59"},
      "e56a8d2fb0484f0b86ad3a94389ef465":{
        "scriptId":"u60"},
      "cb26296822be4e539ded7ecd07f0d6b6":{
        "scriptId":"u61"},
      "2b2a98b7702940e68e6fe36508996623":{
        "scriptId":"u62"},
      "78f6bea1ad7a458bb2d642e92525820c":{
        "scriptId":"u63"},
      "ff99c73ae4004435ae6fe0c8cd92ca82":{
        "scriptId":"u64"},
      "9594b99a48b649a9ac16863410d49a29":{
        "scriptId":"u65"},
      "5ab63e881b09490988e4b99e0d3aa6ec":{
        "scriptId":"u66"},
      "eacd537df0cf486aaa676df80f6f1c85":{
        "scriptId":"u67"},
      "dac0e162aae54759a2365550fa20ad90":{
        "scriptId":"u68"},
      "bf92882fbd124156befb3011315b6813":{
        "scriptId":"u69"},
      "81d034bfa1234cf08900eaab107cc979":{
        "scriptId":"u70"},
      "ef4c44d228214f0cbc2663ab771f63d8":{
        "scriptId":"u71"},
      "940d47e618334bf6bf5809632d96dd65":{
        "scriptId":"u72"},
      "6549f050a6984f49924ccd5f689f98df":{
        "scriptId":"u73"},
      "43f6ad0df5144d41b7a4a0e3cfdbe563":{
        "scriptId":"u74"},
      "10da916a0dc04ed3a22c7f1a715a4e41":{
        "scriptId":"u75"},
      "37b20c2daeaf4394a7f3cc1a901e4f72":{
        "scriptId":"u76"},
      "f238a7c00608449bb521bfd615495994":{
        "scriptId":"u77"},
      "1cde682b88fb4638827a57e1cdd2e681":{
        "scriptId":"u78"},
      "3196c34ec8304a3399ce08e7b106b539":{
        "scriptId":"u79"},
      "1d730ee9d34948aa977a69d4d0ca511f":{
        "scriptId":"u80"},
      "f7bdd736b16c4396884c759966a562d2":{
        "scriptId":"u81"},
      "e25ec83952df4eec9abaf9ce463f9c20":{
        "scriptId":"u82"},
      "3200eabbebe44086a718e9aaa5fefe3b":{
        "scriptId":"u83"},
      "b3dcdd1b50ca4d59ba84c23b7273cc1a":{
        "scriptId":"u84"},
      "198b730695324146a08c3129b1e5de72":{
        "scriptId":"u85"}},
    "caca4f7a8cf847a194268ed7ce626d1e":{
      "scriptId":"u86",
      "e4996488ed8b430bb0cc8e2cc4304738":{
        "scriptId":"u87"},
      "0ab1a2c40f714d4da951cce312690e4c":{
        "scriptId":"u88"}},
    "4d6d551443634650a578295415e94784":{
      "scriptId":"u89",
      "e4996488ed8b430bb0cc8e2cc4304738":{
        "scriptId":"u90"},
      "0ab1a2c40f714d4da951cce312690e4c":{
        "scriptId":"u91"}},
    "b36163aa160c4dc89b78685dc934a3bb":{
      "scriptId":"u92"},
    "48ea9fd4ad8441309f40442cbbde4e4c":{
      "scriptId":"u93"},
    "c7ddaa6eaf1a4834b2a07cf3053b5ec5":{
      "scriptId":"u94"},
    "a899e20cde164fb5b42f9ea8d4d67be9":{
      "scriptId":"u95"},
    "1cf9c591d956497f959c91947aacd5a1":{
      "scriptId":"u96"}}});