$axure.loadCurrentPage({
  "url":"重置密码.html",
  "generationDate":new Date(1448888328834.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b10356deae714d67b2c239c4fe88f074",
    "type":"Axure:Page",
    "name":"重置密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"99ad953d89924dfc9e78ea85d5e7d91d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":10},
            "size":{
              "width":420,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddea130a0f3140bfa126f428ab566061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":10},
                "size":{
                  "width":420,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"0c9d93883d1741d99672074ffe800be5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF029CDD},
            "location":{
              "x":180,
              "y":33},
            "size":{
              "width":420,
              "height":64},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e32dff832574d3dac89809841384bd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF029CDD},
                "location":{
                  "x":180,
                  "y":33},
                "size":{
                  "width":420,
                  "height":64},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"d800fb89e4c341fe830d5e0f62254216",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":201,
              "y":51},
            "size":{
              "width":22,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41439c84c2ad4cc4b3b85bbbeb7e65c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":51},
                "size":{
                  "width":22,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"306013be6835455fb2ee94e8ee929fd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":335,
              "y":58},
            "size":{
              "width":109,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36e65cd9242947f19ce6bc5ec75a099e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":335,
                  "y":58},
                "size":{
                  "width":109,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e603fe3300e34b07bef8ea35264bd366",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":96},
            "size":{
              "width":420,
              "height":655}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["a16944fc8d234b38b48b17c3b494a042"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If area of 移动 未接触 area of 刷新)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["a16944fc8d234b38b48b17c3b494a042"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["c41a61c2c2e148e4865fed55d443a99d"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 到 (0,-60) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["a16944fc8d234b38b48b17c3b494a042"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-60",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4985d886606846f78af6cd55c014e731",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a16944fc8d234b38b48b17c3b494a042",
                  "label":"移动",
                  "parentDynamicPanel":"e603fe3300e34b07bef8ea35264bd366",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-60},
                    "size":{
                      "width":420,
                      "height":1100}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"fd8898a8beac4a9fa46385879ba60f1e",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"f595f51f0b6f404d85eff8b627108903",
                          "label":"",
                          "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "location":{
                              "x":0,
                              "y":113},
                            "size":{
                              "width":420,
                              "height":40},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3ab7ee73b9d643c4a988bc433269be87",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "location":{
                                  "x":0,
                                  "y":113},
                                "size":{
                                  "width":420,
                                  "height":40},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/登录/u10.png"}},
{
                          "id":"62575b1b82504da684f9c76f61b97be3",
                          "label":"",
                          "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "hint":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF6B6B6B,
                                  "opacity":1}}},
                            "location":{
                              "x":122,
                              "y":121},
                            "size":{
                              "width":210,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "placeholderText":"请再次输入密码"},
{
                          "id":"48fcba48028943bca71703a0d725b6c5",
                          "label":"",
                          "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontSize":"14px",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFFFFFF,
                              "opacity":1},
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFF9A14},
                            "location":{
                              "x":17,
                              "y":170},
                            "size":{
                              "width":383,
                              "height":35},
                            "borderWidth":"-1",
                            "cornerRadiusTopLeft":"2"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"0c9b1e98b41e45faa43872032fdb8401",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontSize":"14px",
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFFFFFF,
                                  "opacity":1},
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFFF9A14},
                                "location":{
                                  "x":17,
                                  "y":170},
                                "size":{
                                  "width":383,
                                  "height":35},
                                "borderWidth":"-1",
                                "cornerRadiusTopLeft":"2"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 个人中心",
                                      "target":{
                                        "targetType":"page",
                                        "url":"个人中心.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/登录/u13.png"}},
{
                          "id":"0ce84caabf42410bb2fddd425aee0ea4",
                          "label":"",
                          "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "location":{
                              "x":0,
                              "y":67},
                            "size":{
                              "width":420,
                              "height":40},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1b8945f8181b42759bd210e8f30ce0e9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "location":{
                                  "x":0,
                                  "y":67},
                                "size":{
                                  "width":420,
                                  "height":40},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/登录/u10.png"}},
{
                          "id":"52a3c0832edc439db8d23cac39622900",
                          "label":"",
                          "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                          "type":"textBox",
                          "styleType":"textBox",
                          "visible":true,
                          "style":{
                            "stateStyles":{
                              "hint":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF6B6B6B,
                                  "opacity":1}}},
                            "location":{
                              "x":123,
                              "y":75},
                            "size":{
                              "width":210,
                              "height":25}},
                          "adaptiveStyles":{
},
                          "placeholderText":"请输入密码"},
{
                          "id":"de94b1edff9145ccbe80db6eb212504a",
                          "label":"",
                          "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF6B6B6B,
                              "opacity":1},
                            "size":{
                              "width":420,
                              "height":60},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"b47e8099d0ba488d9a1e82aa3aa238ca",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"a16944fc8d234b38b48b17c3b494a042",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF6B6B6B,
                                  "opacity":1},
                                "size":{
                                  "width":420,
                                  "height":60},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页-跟团游/u57.png"}}]}]},
{
                  "id":"c41a61c2c2e148e4865fed55d443a99d",
                  "label":"刷新",
                  "parentDynamicPanel":"e603fe3300e34b07bef8ea35264bd366",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":180,
                      "y":-100},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"dfc4e4b371f646a5aee37614bed5f577",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[]}]}]}]},
{
          "id":"a331fa48256a4a3f90b18acca3778a4e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":51}},
          "adaptiveStyles":{
},
          "masterId":"24ee36a07ae6402996d787d05dbe2333"}]}},
  "masters":{
    "24ee36a07ae6402996d787d05dbe2333":{
      "packageId":"24ee36a07ae6402996d787d05dbe2333",
      "type":"Axure:Master",
      "name":"返回",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8a8660bc8f04408a89ed1f262f385543",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":22,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"60071eeef6464733864d3bee00e4500d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":22,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "99ad953d89924dfc9e78ea85d5e7d91d":{
      "scriptId":"u0"},
    "ddea130a0f3140bfa126f428ab566061":{
      "scriptId":"u1"},
    "0c9d93883d1741d99672074ffe800be5":{
      "scriptId":"u2"},
    "8e32dff832574d3dac89809841384bd1":{
      "scriptId":"u3"},
    "d800fb89e4c341fe830d5e0f62254216":{
      "scriptId":"u4"},
    "41439c84c2ad4cc4b3b85bbbeb7e65c7":{
      "scriptId":"u5"},
    "306013be6835455fb2ee94e8ee929fd4":{
      "scriptId":"u6"},
    "36e65cd9242947f19ce6bc5ec75a099e":{
      "scriptId":"u7"},
    "e603fe3300e34b07bef8ea35264bd366":{
      "scriptId":"u8"},
    "a16944fc8d234b38b48b17c3b494a042":{
      "scriptId":"u9"},
    "f595f51f0b6f404d85eff8b627108903":{
      "scriptId":"u10"},
    "3ab7ee73b9d643c4a988bc433269be87":{
      "scriptId":"u11"},
    "62575b1b82504da684f9c76f61b97be3":{
      "scriptId":"u12"},
    "48fcba48028943bca71703a0d725b6c5":{
      "scriptId":"u13"},
    "0c9b1e98b41e45faa43872032fdb8401":{
      "scriptId":"u14"},
    "0ce84caabf42410bb2fddd425aee0ea4":{
      "scriptId":"u15"},
    "1b8945f8181b42759bd210e8f30ce0e9":{
      "scriptId":"u16"},
    "52a3c0832edc439db8d23cac39622900":{
      "scriptId":"u17"},
    "de94b1edff9145ccbe80db6eb212504a":{
      "scriptId":"u18"},
    "b47e8099d0ba488d9a1e82aa3aa238ca":{
      "scriptId":"u19"},
    "c41a61c2c2e148e4865fed55d443a99d":{
      "scriptId":"u20"},
    "a331fa48256a4a3f90b18acca3778a4e":{
      "scriptId":"u21",
      "8a8660bc8f04408a89ed1f262f385543":{
        "scriptId":"u22"},
      "60071eeef6464733864d3bee00e4500d":{
        "scriptId":"u23"}}}});