$axure.loadCurrentPage({
  "url":"编辑专题推荐_1.html",
  "generationDate":new Date(1448893834595.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"56f8b429895d45598b03aa68b7fe375e",
    "type":"Axure:Page",
    "name":"编辑专题推荐",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"318b0955f1d749308480f080d8f13ff4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0x99797979},
            "size":{
              "width":1400,
              "height":780},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9380b43274bc40fdaadaad5c665a374c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0x99797979},
                "size":{
                  "width":1400,
                  "height":780},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑专题推荐_1/u0.png"}},
{
          "id":"2369adc0d005441ca048acafbf7beed2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "size":{
              "width":1400,
              "height":100}},
          "adaptiveStyles":{
},
          "masterId":"8f4719ebdd3047f8b8849ec374f2daa3"},
{
          "id":"f3e23574e8914895add39075ccfe62f2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":67.5},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"b0697a20565244c5afbf20c60a1c5e9d"},
{
          "id":"bdf028daa7c0453083541e81f4da78c9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":-11,
              "y":63},
            "size":{
              "width":1,
              "height":1}},
          "adaptiveStyles":{
},
          "masterId":"4b290f55900f4b499fdfdc1a5c8f79df"},
{
          "id":"67198e069bf143be9ee4a2011c24e94f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":66},
            "size":{
              "width":1180,
              "height":694}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b30dba95a5494aa83caad979415c00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":66},
                "size":{
                  "width":1180,
                  "height":694}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑专题推荐_1/u15.png"}},
{
          "id":"dfafc11e1abb48d591a77888390ccbd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":210,
              "y":76},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d7a7e9beedf41e89cc0e22ab58117c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":210,
                  "y":76},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48e3f63c8a0c47acb64fd35d420087e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3366FF,
              "opacity":1},
            "location":{
              "x":306,
              "y":76},
            "size":{
              "width":150,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c50535f463ac43a6b3f92aa6368f885b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3366FF,
                  "opacity":1},
                "location":{
                  "x":306,
                  "y":76},
                "size":{
                  "width":150,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75f61d5f623945fe9ab366379496b278",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":116},
            "size":{
              "width":790,
              "height":495}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80e5655f86eb44d6bdfb262ebefd35db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5e79c5d2fe1476499de0d70ccd41e90",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u24.png"}},
{
              "id":"a155b1effe34424ca1d7ef2bad985584",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":640,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee18c29f866b4256ac109ca45480a4a7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":640,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u26.png"}},
{
              "id":"5f67a3f07e8d4c829f06e2c4f92435cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":35},
                "size":{
                  "width":150,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e015d12b8cd942d6ad87cf88d7b1fe35",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":35},
                    "size":{
                      "width":150,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u24.png"}},
{
              "id":"951e6d290ecd46bf9ee6fd58a4759f72",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":35},
                "size":{
                  "width":640,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"275dd3855e574ac1a7f6cf9bfbf89558",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":35},
                    "size":{
                      "width":640,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u26.png"}},
{
              "id":"f2c6357a12bd4224b7f326d321e7de6d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":150,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"502d9da81dc3456191d87a68fea762a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":150,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u24.png"}},
{
              "id":"59b35ff748ea45db8edaab68e9eaaa81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":320},
                "size":{
                  "width":640,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bc28536727b94a3f8a3db0fa8a9e13f5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":320},
                    "size":{
                      "width":640,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u26.png"}},
{
              "id":"c8434ef4d89547189ba3337ec0009fba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":355},
                "size":{
                  "width":150,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5650242d0f464642b497aa0e082b18bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":355},
                    "size":{
                      "width":150,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u24.png"}},
{
              "id":"dc753c0fd20f4987a76147a7f8c87810",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":355},
                "size":{
                  "width":640,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3c2271ae06b94d0d90e95671d5e6af69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":355},
                    "size":{
                      "width":640,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u26.png"}},
{
              "id":"3140375fb2cd42efb688a03f775ffb92",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":390},
                "size":{
                  "width":150.000015258789,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bce7cc28edeb4e43987f9b6c9fedeec5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":390},
                    "size":{
                      "width":150.000015258789,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u24.png"}},
{
              "id":"4b1a673d70ef4c0a8615f66468df6c4e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":390},
                "size":{
                  "width":640,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50ded62e78904936ad99b43bad00e087",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":390},
                    "size":{
                      "width":640,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u26.png"}},
{
              "id":"f17993017b794e8aadfe9e1f2260fbb8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":70},
                "size":{
                  "width":150,
                  "height":250}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7a3dd232a2a548419c47b00b08134701",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":70},
                    "size":{
                      "width":150,
                      "height":250}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑专题推荐/u30.png"}},
{
              "id":"87f4cdce2f7646f1bd8c7374bc3f7b56",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":70},
                "size":{
                  "width":640,
                  "height":250}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff915c7a9b2f498e91e2a08a538b28b9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":70},
                    "size":{
                      "width":640,
                      "height":250}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑专题推荐/u32.png"}},
{
              "id":"a1b660e6813247c9927cf7f81c7f196a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":460},
                "size":{
                  "width":150,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89afb49118744a88b4ad00a6738bc45d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":460},
                    "size":{
                      "width":150,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u56.png"}},
{
              "id":"2388dddc65704ea5b3121ffc64aa5985",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":460},
                "size":{
                  "width":640,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f109c72472f2424ba074b6295f9591a2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":460},
                    "size":{
                      "width":640,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u58.png"}},
{
              "id":"49095d43fed44a4cbe0b68f785bfff51",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":425},
                "size":{
                  "width":150,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"57b9992273404f8e989c618960714c26",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":425},
                    "size":{
                      "width":150,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u24.png"}},
{
              "id":"5217abab2846476a89f1bdc8996cc82b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":425},
                "size":{
                  "width":640,
                  "height":35}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"53da7c990dcb49c7a8c65321491b4865",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":425},
                    "size":{
                      "width":640,
                      "height":35}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/编辑推荐信息/u26.png"}}]},
{
          "id":"34b716d52c6244eb9925dd277118d1f3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":121},
            "size":{
              "width":513,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9251d037b0fd44909fb152c2b79ae908",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":441},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"018c879d194d4871b2f7ec938b48b0d6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":477},
            "size":{
              "width":180,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3b0fe1cdc68b458dbf93bc55c5f2f33e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":515},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3df58516beaf4f38b340e3c44d82cab9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":367,
                  "y":515},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"33c3fb0c1ac34df480777c5c42c909d9",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":427,
              "y":515},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee31036c3bf4586a20f209cf41bd6fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":427,
                  "y":515},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"92370c51ce0c464dbabc58fb1e2fcd59",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":156},
            "size":{
              "width":513,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"37cff85dd04843c4b1e9a5f4a15a83a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF515151},
            "location":{
              "x":490,
              "y":656},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b23fedcd8070401eb562f5dbf43c0d65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151},
                "location":{
                  "x":490,
                  "y":656},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑推荐信息/u72.png"}},
{
          "id":"770266885cfc472a8b580242ecd65d12",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF515151},
            "location":{
              "x":620,
              "y":656},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6176471ea924e25a75ceb6cea161889",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF515151},
                "location":{
                  "x":620,
                  "y":656},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑推荐信息/u72.png"}},
{
          "id":"945261f39c10447b80614098ebd59eeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":370,
              "y":194},
            "size":{
              "width":500,
              "height":229},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"912ca398461b404eb35012b21349c0d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":370,
                  "y":194},
                "size":{
                  "width":500,
                  "height":229},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑推荐信息/u78.png"}},
{
          "id":"b89593fbc8314469a0d3d0d0eddadb7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF949494},
            "location":{
              "x":514,
              "y":264},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81d17865a3b649d6aed7b165af5e2818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF949494},
                "location":{
                  "x":514,
                  "y":264},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑推荐信息/u80.png"}},
{
          "id":"85f76e329aef49fe938b133878c18b56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF868686,
              "opacity":1},
            "location":{
              "x":401,
              "y":358},
            "size":{
              "width":438,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f45bc98333824c22a991b0085e4166d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF868686,
                  "opacity":1},
                "location":{
                  "x":401,
                  "y":358},
                "size":{
                  "width":438,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e6285ee3c6b4d7ba92c271dfd62d0a5",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":587},
            "size":{
              "width":111,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f08aec156c2841eb9e1d36deead50f17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":587},
                "size":{
                  "width":111,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"6b25d2458ea2481a937c9104825ee5aa",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":367,
              "y":547},
            "size":{
              "width":89,
              "height":22}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "8f4719ebdd3047f8b8849ec374f2daa3":{
      "packageId":"8f4719ebdd3047f8b8849ec374f2daa3",
      "type":"Axure:Master",
      "name":"官方后台（顶部公共部分）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"dc2e67552d87498abb74a89689f16d74",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "fill":{
                "fillType":"solid",
                "color":0xFFD7D7D7},
              "size":{
                "width":1400,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"55e05f16c2a246869dfb22dfe401a760",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFD7D7D7},
                  "size":{
                    "width":1400,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/默认搜索关键词/u8.png"}},
{
            "id":"dafb294aea0c4047bd0376009a18ed06",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF515151,
                "opacity":1},
              "location":{
                "x":1131,
                "y":20},
              "size":{
                "width":240,
                "height":20},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"33653d9a09f343b6bf215ea55a319f31",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF515151,
                    "opacity":1},
                  "location":{
                    "x":1131,
                    "y":20},
                  "size":{
                    "width":240,
                    "height":20},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1dab3103e78f4ca29bdb3c94806279e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF3333FF,
                "opacity":1},
              "location":{
                "x":1322,
                "y":20},
              "size":{
                "width":60,
                "height":20},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"30cfdd5f3a8a4950be998791f352c3e0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF3333FF,
                    "opacity":1},
                  "location":{
                    "x":1322,
                    "y":20},
                  "size":{
                    "width":60,
                    "height":20},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1e8557e2a5d541fab498f390ff08489f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontSize":"14px",
              "location":{
                "x":10,
                "y":10},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4b1a60be494748d1977f48d47422f477",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"14px",
                  "location":{
                    "x":10,
                    "y":10},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/默认搜索关键词/u14.png"}}]}},
    "b0697a20565244c5afbf20c60a1c5e9d":{
      "packageId":"b0697a20565244c5afbf20c60a1c5e9d",
      "type":"Axure:Master",
      "name":"导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[]}},
    "4b290f55900f4b499fdfdc1a5c8f79df":{
      "packageId":"4b290f55900f4b499fdfdc1a5c8f79df",
      "type":"Axure:Master",
      "name":"营销管理",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d59b1d549f844c3c95a42e221b682a0e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":34,
                "y":46},
              "size":{
                "width":206,
                "height":634}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ccc911ae91434a2cb8bce36acd506317",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":34,
                    "y":46},
                  "size":{
                    "width":206,
                    "height":634}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/默认搜索关键词/u5.png"}}]}}},
  "objectPaths":{
    "318b0955f1d749308480f080d8f13ff4":{
      "scriptId":"u0"},
    "9380b43274bc40fdaadaad5c665a374c":{
      "scriptId":"u1"},
    "2369adc0d005441ca048acafbf7beed2":{
      "scriptId":"u2",
      "dc2e67552d87498abb74a89689f16d74":{
        "scriptId":"u3"},
      "55e05f16c2a246869dfb22dfe401a760":{
        "scriptId":"u4"},
      "dafb294aea0c4047bd0376009a18ed06":{
        "scriptId":"u5"},
      "33653d9a09f343b6bf215ea55a319f31":{
        "scriptId":"u6"},
      "1dab3103e78f4ca29bdb3c94806279e2":{
        "scriptId":"u7"},
      "30cfdd5f3a8a4950be998791f352c3e0":{
        "scriptId":"u8"},
      "1e8557e2a5d541fab498f390ff08489f":{
        "scriptId":"u9"},
      "4b1a60be494748d1977f48d47422f477":{
        "scriptId":"u10"}},
    "f3e23574e8914895add39075ccfe62f2":{
      "scriptId":"u11"},
    "bdf028daa7c0453083541e81f4da78c9":{
      "scriptId":"u12",
      "d59b1d549f844c3c95a42e221b682a0e":{
        "scriptId":"u13"},
      "ccc911ae91434a2cb8bce36acd506317":{
        "scriptId":"u14"}},
    "67198e069bf143be9ee4a2011c24e94f":{
      "scriptId":"u15"},
    "09b30dba95a5494aa83caad979415c00":{
      "scriptId":"u16"},
    "dfafc11e1abb48d591a77888390ccbd1":{
      "scriptId":"u17"},
    "4d7a7e9beedf41e89cc0e22ab58117c6":{
      "scriptId":"u18"},
    "48e3f63c8a0c47acb64fd35d420087e6":{
      "scriptId":"u19"},
    "c50535f463ac43a6b3f92aa6368f885b":{
      "scriptId":"u20"},
    "75f61d5f623945fe9ab366379496b278":{
      "scriptId":"u21"},
    "80e5655f86eb44d6bdfb262ebefd35db":{
      "scriptId":"u22"},
    "d5e79c5d2fe1476499de0d70ccd41e90":{
      "scriptId":"u23"},
    "a155b1effe34424ca1d7ef2bad985584":{
      "scriptId":"u24"},
    "ee18c29f866b4256ac109ca45480a4a7":{
      "scriptId":"u25"},
    "5f67a3f07e8d4c829f06e2c4f92435cc":{
      "scriptId":"u26"},
    "e015d12b8cd942d6ad87cf88d7b1fe35":{
      "scriptId":"u27"},
    "951e6d290ecd46bf9ee6fd58a4759f72":{
      "scriptId":"u28"},
    "275dd3855e574ac1a7f6cf9bfbf89558":{
      "scriptId":"u29"},
    "f17993017b794e8aadfe9e1f2260fbb8":{
      "scriptId":"u30"},
    "7a3dd232a2a548419c47b00b08134701":{
      "scriptId":"u31"},
    "87f4cdce2f7646f1bd8c7374bc3f7b56":{
      "scriptId":"u32"},
    "ff915c7a9b2f498e91e2a08a538b28b9":{
      "scriptId":"u33"},
    "f2c6357a12bd4224b7f326d321e7de6d":{
      "scriptId":"u34"},
    "502d9da81dc3456191d87a68fea762a5":{
      "scriptId":"u35"},
    "59b35ff748ea45db8edaab68e9eaaa81":{
      "scriptId":"u36"},
    "bc28536727b94a3f8a3db0fa8a9e13f5":{
      "scriptId":"u37"},
    "c8434ef4d89547189ba3337ec0009fba":{
      "scriptId":"u38"},
    "5650242d0f464642b497aa0e082b18bf":{
      "scriptId":"u39"},
    "dc753c0fd20f4987a76147a7f8c87810":{
      "scriptId":"u40"},
    "3c2271ae06b94d0d90e95671d5e6af69":{
      "scriptId":"u41"},
    "3140375fb2cd42efb688a03f775ffb92":{
      "scriptId":"u42"},
    "bce7cc28edeb4e43987f9b6c9fedeec5":{
      "scriptId":"u43"},
    "4b1a673d70ef4c0a8615f66468df6c4e":{
      "scriptId":"u44"},
    "50ded62e78904936ad99b43bad00e087":{
      "scriptId":"u45"},
    "49095d43fed44a4cbe0b68f785bfff51":{
      "scriptId":"u46"},
    "57b9992273404f8e989c618960714c26":{
      "scriptId":"u47"},
    "5217abab2846476a89f1bdc8996cc82b":{
      "scriptId":"u48"},
    "53da7c990dcb49c7a8c65321491b4865":{
      "scriptId":"u49"},
    "a1b660e6813247c9927cf7f81c7f196a":{
      "scriptId":"u50"},
    "89afb49118744a88b4ad00a6738bc45d":{
      "scriptId":"u51"},
    "2388dddc65704ea5b3121ffc64aa5985":{
      "scriptId":"u52"},
    "f109c72472f2424ba074b6295f9591a2":{
      "scriptId":"u53"},
    "34b716d52c6244eb9925dd277118d1f3":{
      "scriptId":"u54"},
    "9251d037b0fd44909fb152c2b79ae908":{
      "scriptId":"u55"},
    "018c879d194d4871b2f7ec938b48b0d6":{
      "scriptId":"u56"},
    "3b0fe1cdc68b458dbf93bc55c5f2f33e":{
      "scriptId":"u57"},
    "3df58516beaf4f38b340e3c44d82cab9":{
      "scriptId":"u58"},
    "33c3fb0c1ac34df480777c5c42c909d9":{
      "scriptId":"u59"},
    "4ee31036c3bf4586a20f209cf41bd6fa":{
      "scriptId":"u60"},
    "92370c51ce0c464dbabc58fb1e2fcd59":{
      "scriptId":"u61"},
    "37cff85dd04843c4b1e9a5f4a15a83a1":{
      "scriptId":"u62"},
    "b23fedcd8070401eb562f5dbf43c0d65":{
      "scriptId":"u63"},
    "770266885cfc472a8b580242ecd65d12":{
      "scriptId":"u64"},
    "b6176471ea924e25a75ceb6cea161889":{
      "scriptId":"u65"},
    "945261f39c10447b80614098ebd59eeb":{
      "scriptId":"u66"},
    "912ca398461b404eb35012b21349c0d1":{
      "scriptId":"u67"},
    "b89593fbc8314469a0d3d0d0eddadb7d":{
      "scriptId":"u68"},
    "81d17865a3b649d6aed7b165af5e2818":{
      "scriptId":"u69"},
    "85f76e329aef49fe938b133878c18b56":{
      "scriptId":"u70"},
    "f45bc98333824c22a991b0085e4166d5":{
      "scriptId":"u71"},
    "1e6285ee3c6b4d7ba92c271dfd62d0a5":{
      "scriptId":"u72"},
    "f08aec156c2841eb9e1d36deead50f17":{
      "scriptId":"u73"},
    "6b25d2458ea2481a937c9104825ee5aa":{
      "scriptId":"u74"}}});