$axure.loadCurrentPage({
  "url":"支付成功.html",
  "generationDate":new Date(1448888324960.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a7a35f8e1de8479382bbd8dba7c85703",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"117cc0b9ae8247ffb9b1ed61e74d9749",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":10},
            "size":{
              "width":420,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08c03d2da00b4c0f85d58b11a3db23a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":10},
                "size":{
                  "width":420,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"8f8eeb87611f44939e72aedab2df1472",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF029CDD},
            "location":{
              "x":180,
              "y":33},
            "size":{
              "width":420,
              "height":64},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7233af71884b718280981e04963a76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF029CDD},
                "location":{
                  "x":180,
                  "y":33},
                "size":{
                  "width":420,
                  "height":64},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u2.png"}},
{
          "id":"3b5c3128a3304fedbe3490c6848e40d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":201,
              "y":51},
            "size":{
              "width":22,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c71a5747c194348a3f99f038a35cfc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":201,
                  "y":51},
                "size":{
                  "width":22,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13b4d107dd1f4a888f94748e40fa3155",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":350,
              "y":57},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc5b8b32d3b4baeb479ecea60cf8fe2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":350,
                  "y":57},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1e9c6f6c6334aa18374ad2d2d6d805a",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":96},
            "size":{
              "width":420,
              "height":655}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["1cb688ea08cb4f7e96dff23e15faaf97"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onDragDrop":{
              "description":"OnDragDrop",
              "cases":[{
                  "description":"用例 1<br> (If area of 移动 未接触 area of 刷新)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["1cb688ea08cb4f7e96dff23e15faaf97"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["89955588fab44e1a9ca9d5457ff6ed47"]}]}]},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 移动 到 (0,-60) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["1cb688ea08cb4f7e96dff23e15faaf97"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-60",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6d67e4addec548a488f55a9f3a97c39a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1cb688ea08cb4f7e96dff23e15faaf97",
                  "label":"移动",
                  "parentDynamicPanel":"c1e9c6f6c6334aa18374ad2d2d6d805a",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-60},
                    "size":{
                      "width":420,
                      "height":800}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"bc393b0c5d984a118c71ebb9cba3022b",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"b2cb066b5c394b1f9012736ed0e4341d",
                          "label":"",
                          "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":0,
                              "y":60},
                            "size":{
                              "width":420,
                              "height":160},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ca477ab97d0b4ef2a881b6a431a78629",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":0,
                                  "y":60},
                                "size":{
                                  "width":420,
                                  "height":160},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/支付成功/u10.png"}},
{
                          "id":"5dcc7647af044e6a84ffc9fe7003e1d5",
                          "label":"",
                          "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFA1A1A1,
                              "opacity":1},
                            "location":{
                              "x":94,
                              "y":172},
                            "size":{
                              "width":235,
                              "height":16},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFC9C9C9}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ec75e59eccf7445cbf07dcf1ba4fa60c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFA1A1A1,
                                  "opacity":1},
                                "location":{
                                  "x":94,
                                  "y":172},
                                "size":{
                                  "width":235,
                                  "height":16},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFC9C9C9}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}},
{
                          "id":"349b2c1f25374a948bdf06923e2f6368",
                          "label":"",
                          "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFCC33FF,
                              "opacity":1},
                            "location":{
                              "x":70,
                              "y":250},
                            "size":{
                              "width":110,
                              "height":35},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCC66FF},
                            "cornerRadiusTopLeft":"2"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"e839c3b848d541458f9d307d65e1e36a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFCC33FF,
                                  "opacity":1},
                                "location":{
                                  "x":70,
                                  "y":250},
                                "size":{
                                  "width":110,
                                  "height":35},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCC66FF},
                                "cornerRadiusTopLeft":"2"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 订单详情-已成功",
                                      "target":{
                                        "targetType":"page",
                                        "url":"订单详情-已成功.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/支付成功/u14.png"}},
{
                          "id":"013f68a00e92469e9134bcc8023a2a78",
                          "label":"",
                          "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFCC33FF,
                              "opacity":1},
                            "location":{
                              "x":219,
                              "y":250},
                            "size":{
                              "width":110,
                              "height":35},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCC66FF},
                            "cornerRadiusTopLeft":"2"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"82e681aeb1b8443697a551a6e36cfc9e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFCC33FF,
                                  "opacity":1},
                                "location":{
                                  "x":219,
                                  "y":250},
                                "size":{
                                  "width":110,
                                  "height":35},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCC66FF},
                                "cornerRadiusTopLeft":"2"},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"linkWindow",
                                      "description":"在 当前窗口 打开 首页",
                                      "target":{
                                        "targetType":"page",
                                        "url":"首页.html",
                                        "includeVariables":true},
                                      "linkType":"current"}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/支付成功/u14.png"}},
{
                          "id":"3900ce0df27046a7b190600bfa53ea66",
                          "label":"",
                          "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF6B6B6B,
                              "opacity":1},
                            "size":{
                              "width":420,
                              "height":60},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9d768e96ffc64d7583efcc70b10cdc87",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1cb688ea08cb4f7e96dff23e15faaf97",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF6B6B6B,
                                  "opacity":1},
                                "size":{
                                  "width":420,
                                  "height":60},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页-跟团游/u57.png"}}]}]},
{
                  "id":"89955588fab44e1a9ca9d5457ff6ed47",
                  "label":"刷新",
                  "parentDynamicPanel":"c1e9c6f6c6334aa18374ad2d2d6d805a",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":180,
                      "y":-100},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"8de3aa34a67a4fdeaf7652e7752a4734",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[]}]}]}]},
{
          "id":"1a9aa8bb3fa246cf92af011f3323b6a2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":201,
              "y":51}},
          "adaptiveStyles":{
},
          "masterId":"24ee36a07ae6402996d787d05dbe2333"},
{
          "id":"f9e5854acf314394bf15a1cd34b7d46a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":536,
              "y":46},
            "size":{
              "width":47,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25300cf23f8943deb2dc2c2bd216548c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":536,
                  "y":46},
                "size":{
                  "width":47,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-跟团游/u7.png"}}]}},
  "masters":{
    "24ee36a07ae6402996d787d05dbe2333":{
      "packageId":"24ee36a07ae6402996d787d05dbe2333",
      "type":"Axure:Master",
      "name":"返回",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8a8660bc8f04408a89ed1f262f385543",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"36px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "size":{
                "width":22,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"60071eeef6464733864d3bee00e4500d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"36px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "size":{
                    "width":22,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "117cc0b9ae8247ffb9b1ed61e74d9749":{
      "scriptId":"u0"},
    "08c03d2da00b4c0f85d58b11a3db23a8":{
      "scriptId":"u1"},
    "8f8eeb87611f44939e72aedab2df1472":{
      "scriptId":"u2"},
    "9f7233af71884b718280981e04963a76":{
      "scriptId":"u3"},
    "3b5c3128a3304fedbe3490c6848e40d8":{
      "scriptId":"u4"},
    "5c71a5747c194348a3f99f038a35cfc3":{
      "scriptId":"u5"},
    "13b4d107dd1f4a888f94748e40fa3155":{
      "scriptId":"u6"},
    "3cc5b8b32d3b4baeb479ecea60cf8fe2":{
      "scriptId":"u7"},
    "c1e9c6f6c6334aa18374ad2d2d6d805a":{
      "scriptId":"u8"},
    "1cb688ea08cb4f7e96dff23e15faaf97":{
      "scriptId":"u9"},
    "b2cb066b5c394b1f9012736ed0e4341d":{
      "scriptId":"u10"},
    "ca477ab97d0b4ef2a881b6a431a78629":{
      "scriptId":"u11"},
    "5dcc7647af044e6a84ffc9fe7003e1d5":{
      "scriptId":"u12"},
    "ec75e59eccf7445cbf07dcf1ba4fa60c":{
      "scriptId":"u13"},
    "349b2c1f25374a948bdf06923e2f6368":{
      "scriptId":"u14"},
    "e839c3b848d541458f9d307d65e1e36a":{
      "scriptId":"u15"},
    "013f68a00e92469e9134bcc8023a2a78":{
      "scriptId":"u16"},
    "82e681aeb1b8443697a551a6e36cfc9e":{
      "scriptId":"u17"},
    "3900ce0df27046a7b190600bfa53ea66":{
      "scriptId":"u18"},
    "9d768e96ffc64d7583efcc70b10cdc87":{
      "scriptId":"u19"},
    "89955588fab44e1a9ca9d5457ff6ed47":{
      "scriptId":"u20"},
    "1a9aa8bb3fa246cf92af011f3323b6a2":{
      "scriptId":"u21",
      "8a8660bc8f04408a89ed1f262f385543":{
        "scriptId":"u22"},
      "60071eeef6464733864d3bee00e4500d":{
        "scriptId":"u23"}},
    "f9e5854acf314394bf15a1cd34b7d46a":{
      "scriptId":"u24"},
    "25300cf23f8943deb2dc2c2bd216548c":{
      "scriptId":"u25"}}});